import type { SensorPreset, SensorPresetKey } from "./types";

export const SENSOR_PRESETS: Record<SensorPresetKey, SensorPreset> = {
  custom: {
    label: "Custom",
    hint: "No defaults applied.",
    driver: "analog",
    unit: "V",
    interval_seconds: 30,
    rolling_average_seconds: 0,
    defaultName: "Custom Sensor",
  },
  temperature: {
    label: "Temperature",
    hint: "15m interval with 15m rolling average.",
    driver: "analog",
    unit: "°C",
    interval_seconds: 900,
    rolling_average_seconds: 900,
    defaultName: "Temperature",
    input_min: 0,
    input_max: 3.3,
    output_min: -20,
    output_max: 80,
  },
  soil_moisture: {
    label: "Soil Moisture",
    hint: "15m interval with 15m rolling average.",
    driver: "analog",
    unit: "%",
    interval_seconds: 900,
    rolling_average_seconds: 900,
    defaultName: "Soil Moisture",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 100,
  },
  soil_temperature: {
    label: "Soil Temperature",
    hint: "15m interval with 15m rolling average.",
    driver: "analog",
    unit: "°C",
    interval_seconds: 900,
    rolling_average_seconds: 900,
    defaultName: "Soil Temperature",
    input_min: 0,
    input_max: 3.3,
    output_min: -20,
    output_max: 80,
  },
  moisture: {
    label: "Moisture",
    hint: "15m interval with 15m rolling average.",
    driver: "analog",
    unit: "%",
    interval_seconds: 900,
    rolling_average_seconds: 900,
    defaultName: "Moisture",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 100,
  },
  humidity: {
    label: "Humidity",
    hint: "15m interval with 15m rolling average.",
    driver: "analog",
    unit: "%",
    interval_seconds: 900,
    rolling_average_seconds: 900,
    defaultName: "Humidity",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 100,
  },
  pressure: {
    label: "Pressure",
    hint: "60s interval with 60s rolling average.",
    driver: "analog",
    unit: "psi",
    interval_seconds: 60,
    rolling_average_seconds: 60,
    defaultName: "Pressure",
    input_min: 1,
    input_max: 6,
    output_min: 0,
    output_max: 300,
  },
  pressure_4_20ma_300psi: {
    label: "Pressure (4–20mA · 0–300 psi)",
    hint: "60s interval with 60s rolling average. Configure the shunt so the input is in mA.",
    driver: "analog",
    unit: "psi",
    interval_seconds: 60,
    rolling_average_seconds: 60,
    defaultName: "Pressure",
    input_min: 4,
    input_max: 20,
    output_min: 0,
    output_max: 300,
  },
  wind_speed: {
    label: "Wind Speed",
    hint: "60s interval with 60s rolling average.",
    driver: "analog",
    unit: "mph",
    interval_seconds: 60,
    rolling_average_seconds: 60,
    defaultName: "Wind Speed",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 100,
  },
  wind_direction: {
    label: "Wind Direction",
    hint: "60s interval with 60s rolling average.",
    driver: "analog",
    unit: "deg",
    interval_seconds: 60,
    rolling_average_seconds: 60,
    defaultName: "Wind Direction",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 360,
  },
  solar_irradiance: {
    label: "Solar Irradiance",
    hint: "60s interval with 60s rolling average.",
    driver: "analog",
    unit: "W/m2",
    interval_seconds: 60,
    rolling_average_seconds: 60,
    defaultName: "Solar Irradiance",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 1400,
  },
  lux: {
    label: "Lux",
    hint: "60s interval with 60s rolling average.",
    driver: "analog",
    unit: "lux",
    interval_seconds: 60,
    rolling_average_seconds: 60,
    defaultName: "Lux",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 100000,
  },
  rain_gauge: {
    label: "Rain Gauge (pulse · inches)",
    hint: "COV logging (interval 0). Typical tipping bucket: 0.2794 in / tip.",
    driver: "pulse",
    unit: "in",
    interval_seconds: 0,
    rolling_average_seconds: 0,
    defaultName: "Rain Gauge",
    pulses_per_unit: 3.58, // pulses per inch (1 / 0.2794 in per tip)
  },
  rain_gauge_inches: {
    label: "Rain Gauge (pulse · 0.2794 in/tip)",
    hint: "COV logging (interval 0). Same as above, but explicit unit/tip size.",
    driver: "pulse",
    unit: "in",
    interval_seconds: 0,
    rolling_average_seconds: 0,
    defaultName: "Rain Gauge",
    pulses_per_unit: 3.58, // pulses per inch (1 / 0.2794)
  },
  flow_meter: {
    label: "Flow Meter (pulse)",
    hint: "COV logging (interval 0).",
    driver: "pulse",
    unit: "gpm",
    interval_seconds: 0,
    rolling_average_seconds: 0,
    defaultName: "Flow Meter",
    pulses_per_unit: 450.0,
  },
  flow_meter_gallons: {
    label: "Water Meter (pulse · gallons)",
    hint: "COV logging (interval 0). Set pulses_per_unit to pulses per gallon.",
    driver: "pulse",
    unit: "gal",
    interval_seconds: 0,
    rolling_average_seconds: 0,
    defaultName: "Water Meter",
    pulses_per_unit: 450.0,
  },
  power_kw: {
    label: "Power (kW)",
    hint: "1s interval with 60s rolling average.",
    driver: "analog",
    unit: "kW",
    interval_seconds: 1,
    rolling_average_seconds: 60,
    defaultName: "Power",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 25,
  },
  water_level: {
    label: "Reservoir Depth (4–20mA · 0–5m)",
    hint: "Publishes ~2 Hz using a 4–20mA current-loop transducer across a shunt resistor. Faults are fail-closed (no telemetry).",
    driver: "analog",
    unit: "ft",
    interval_seconds: 0.5,
    rolling_average_seconds: 0,
    defaultName: "Reservoir Depth",
    current_loop_shunt_ohms: 163.0,
    current_loop_range_m: 5.0,
  },
  water_level_4_20ma_240in: {
    label: "Water Level (4–20mA · 0–240 in)",
    hint: "COV logging (interval 0). Configure the shunt so the input is in mA.",
    driver: "analog",
    unit: "in",
    interval_seconds: 0,
    rolling_average_seconds: 0,
    defaultName: "Water Level",
    input_min: 4,
    input_max: 20,
    output_min: 0,
    output_max: 240,
  },
  fertilizer_level: {
    label: "Fertilizer/Chemical Level",
    hint: "15m interval with 15m rolling average.",
    driver: "analog",
    unit: "%",
    interval_seconds: 900,
    rolling_average_seconds: 900,
    defaultName: "Fertilizer Level",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 100,
  },
  current: {
    label: "Current",
    hint: "1s interval with 60s rolling average.",
    driver: "analog",
    unit: "A",
    interval_seconds: 1,
    rolling_average_seconds: 60,
    defaultName: "Current",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 20,
  },
  voltage: {
    label: "Voltage",
    hint: "1s interval with 60s rolling average.",
    driver: "analog",
    unit: "V",
    interval_seconds: 1,
    rolling_average_seconds: 60,
    defaultName: "Voltage",
    input_min: 0,
    input_max: 3.3,
    output_min: 0,
    output_max: 240,
  },
};
