/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionLogResponse
 */
export interface ActionLogResponse {
    /**
     * 
     * @type {any}
     * @memberof ActionLogResponse
     */
    action: any | null;
    /**
     * 
     * @type {string}
     * @memberof ActionLogResponse
     */
    created_at: string;
    /**
     * 
     * @type {string}
     * @memberof ActionLogResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ActionLogResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActionLogResponse
     */
    node_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActionLogResponse
     */
    output_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActionLogResponse
     */
    schedule_id: string;
    /**
     * 
     * @type {string}
     * @memberof ActionLogResponse
     */
    status: string;
}

/**
 * Check if a given object implements the ActionLogResponse interface.
 */
export function instanceOfActionLogResponse(value: object): value is ActionLogResponse {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('schedule_id' in value) || value['schedule_id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ActionLogResponseFromJSON(json: any): ActionLogResponse {
    return ActionLogResponseFromJSONTyped(json, false);
}

export function ActionLogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionLogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'created_at': json['created_at'],
        'id': json['id'],
        'message': json['message'] == null ? undefined : json['message'],
        'node_id': json['node_id'] == null ? undefined : json['node_id'],
        'output_id': json['output_id'] == null ? undefined : json['output_id'],
        'schedule_id': json['schedule_id'],
        'status': json['status'],
    };
}

export function ActionLogResponseToJSON(json: any): ActionLogResponse {
    return ActionLogResponseToJSONTyped(json, false);
}

export function ActionLogResponseToJSONTyped(value?: ActionLogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'created_at': value['created_at'],
        'id': value['id'],
        'message': value['message'],
        'node_id': value['node_id'],
        'output_id': value['output_id'],
        'schedule_id': value['schedule_id'],
        'status': value['status'],
    };
}

