/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdoptionCandidate
 */
export interface AdoptionCandidate {
    /**
     * 
     * @type {string}
     * @memberof AdoptionCandidate
     */
    adoption_token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdoptionCandidate
     */
    hostname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdoptionCandidate
     */
    ip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdoptionCandidate
     */
    mac_eth?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdoptionCandidate
     */
    mac_wifi?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdoptionCandidate
     */
    port?: number | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AdoptionCandidate
     */
    properties: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof AdoptionCandidate
     */
    service_name: string;
}

/**
 * Check if a given object implements the AdoptionCandidate interface.
 */
export function instanceOfAdoptionCandidate(value: object): value is AdoptionCandidate {
    if (!('properties' in value) || value['properties'] === undefined) return false;
    if (!('service_name' in value) || value['service_name'] === undefined) return false;
    return true;
}

export function AdoptionCandidateFromJSON(json: any): AdoptionCandidate {
    return AdoptionCandidateFromJSONTyped(json, false);
}

export function AdoptionCandidateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdoptionCandidate {
    if (json == null) {
        return json;
    }
    return {
        
        'adoption_token': json['adoption_token'] == null ? undefined : json['adoption_token'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'mac_eth': json['mac_eth'] == null ? undefined : json['mac_eth'],
        'mac_wifi': json['mac_wifi'] == null ? undefined : json['mac_wifi'],
        'port': json['port'] == null ? undefined : json['port'],
        'properties': json['properties'],
        'service_name': json['service_name'],
    };
}

export function AdoptionCandidateToJSON(json: any): AdoptionCandidate {
    return AdoptionCandidateToJSONTyped(json, false);
}

export function AdoptionCandidateToJSONTyped(value?: AdoptionCandidate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adoption_token': value['adoption_token'],
        'hostname': value['hostname'],
        'ip': value['ip'],
        'mac_eth': value['mac_eth'],
        'mac_wifi': value['mac_wifi'],
        'port': value['port'],
        'properties': value['properties'],
        'service_name': value['service_name'],
    };
}

