/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlarmRuleDeleteResponse
 */
export interface AlarmRuleDeleteResponse {
    /**
     * 
     * @type {string}
     * @memberof AlarmRuleDeleteResponse
     */
    status: string;
}

/**
 * Check if a given object implements the AlarmRuleDeleteResponse interface.
 */
export function instanceOfAlarmRuleDeleteResponse(value: object): value is AlarmRuleDeleteResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AlarmRuleDeleteResponseFromJSON(json: any): AlarmRuleDeleteResponse {
    return AlarmRuleDeleteResponseFromJSONTyped(json, false);
}

export function AlarmRuleDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlarmRuleDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function AlarmRuleDeleteResponseToJSON(json: any): AlarmRuleDeleteResponse {
    return AlarmRuleDeleteResponseToJSONTyped(json, false);
}

export function AlarmRuleDeleteResponseToJSONTyped(value?: AlarmRuleDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

