/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlarmEventResponse
 */
export interface AlarmEventResponse {
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    alarm_id: string;
    /**
     * 
     * @type {number}
     * @memberof AlarmEventResponse
     */
    anomaly_score?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    created_at?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    incident_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    node_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    origin: string;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    rule_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    sensor_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    target_key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlarmEventResponse
     */
    transition?: string | null;
}

/**
 * Check if a given object implements the AlarmEventResponse interface.
 */
export function instanceOfAlarmEventResponse(value: object): value is AlarmEventResponse {
    if (!('alarm_id' in value) || value['alarm_id'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AlarmEventResponseFromJSON(json: any): AlarmEventResponse {
    return AlarmEventResponseFromJSONTyped(json, false);
}

export function AlarmEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlarmEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'alarm_id': json['alarm_id'],
        'anomaly_score': json['anomaly_score'] == null ? undefined : json['anomaly_score'],
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'],
        'incident_id': json['incident_id'] == null ? undefined : json['incident_id'],
        'message': json['message'] == null ? undefined : json['message'],
        'node_id': json['node_id'] == null ? undefined : json['node_id'],
        'origin': json['origin'],
        'rule_id': json['rule_id'] == null ? undefined : json['rule_id'],
        'sensor_id': json['sensor_id'] == null ? undefined : json['sensor_id'],
        'status': json['status'],
        'target_key': json['target_key'] == null ? undefined : json['target_key'],
        'transition': json['transition'] == null ? undefined : json['transition'],
    };
}

export function AlarmEventResponseToJSON(json: any): AlarmEventResponse {
    return AlarmEventResponseToJSONTyped(json, false);
}

export function AlarmEventResponseToJSONTyped(value?: AlarmEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alarm_id': value['alarm_id'],
        'anomaly_score': value['anomaly_score'],
        'created_at': value['created_at'],
        'id': value['id'],
        'incident_id': value['incident_id'],
        'message': value['message'],
        'node_id': value['node_id'],
        'origin': value['origin'],
        'rule_id': value['rule_id'],
        'sensor_id': value['sensor_id'],
        'status': value['status'],
        'target_key': value['target_key'],
        'transition': value['transition'],
    };
}

