/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsTimeSeriesPoint } from './AnalyticsTimeSeriesPoint';
import {
    AnalyticsTimeSeriesPointFromJSON,
    AnalyticsTimeSeriesPointFromJSONTyped,
    AnalyticsTimeSeriesPointToJSON,
    AnalyticsTimeSeriesPointToJSONTyped,
} from './AnalyticsTimeSeriesPoint';

/**
 * 
 * @export
 * @interface AnalyticsWater
 */
export interface AnalyticsWater {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsWater
     */
    ag_gal_168h: number;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsWater
     */
    ag_series: Array<AnalyticsTimeSeriesPoint>;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsWater
     */
    domestic_gal_168h: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsWater
     */
    domestic_gal_24h: number;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsWater
     */
    domestic_series: Array<AnalyticsTimeSeriesPoint>;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsWater
     */
    reservoir_depth: Array<AnalyticsTimeSeriesPoint>;
}

/**
 * Check if a given object implements the AnalyticsWater interface.
 */
export function instanceOfAnalyticsWater(value: object): value is AnalyticsWater {
    if (!('ag_gal_168h' in value) || value['ag_gal_168h'] === undefined) return false;
    if (!('ag_series' in value) || value['ag_series'] === undefined) return false;
    if (!('domestic_gal_168h' in value) || value['domestic_gal_168h'] === undefined) return false;
    if (!('domestic_gal_24h' in value) || value['domestic_gal_24h'] === undefined) return false;
    if (!('domestic_series' in value) || value['domestic_series'] === undefined) return false;
    if (!('reservoir_depth' in value) || value['reservoir_depth'] === undefined) return false;
    return true;
}

export function AnalyticsWaterFromJSON(json: any): AnalyticsWater {
    return AnalyticsWaterFromJSONTyped(json, false);
}

export function AnalyticsWaterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsWater {
    if (json == null) {
        return json;
    }
    return {
        
        'ag_gal_168h': json['ag_gal_168h'],
        'ag_series': ((json['ag_series'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
        'domestic_gal_168h': json['domestic_gal_168h'],
        'domestic_gal_24h': json['domestic_gal_24h'],
        'domestic_series': ((json['domestic_series'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
        'reservoir_depth': ((json['reservoir_depth'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
    };
}

export function AnalyticsWaterToJSON(json: any): AnalyticsWater {
    return AnalyticsWaterToJSONTyped(json, false);
}

export function AnalyticsWaterToJSONTyped(value?: AnalyticsWater | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ag_gal_168h': value['ag_gal_168h'],
        'ag_series': ((value['ag_series'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
        'domestic_gal_168h': value['domestic_gal_168h'],
        'domestic_gal_24h': value['domestic_gal_24h'],
        'domestic_series': ((value['domestic_series'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
        'reservoir_depth': ((value['reservoir_depth'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
    };
}

