/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsTimeSeriesPoint } from './AnalyticsTimeSeriesPoint';
import {
    AnalyticsTimeSeriesPointFromJSON,
    AnalyticsTimeSeriesPointFromJSONTyped,
    AnalyticsTimeSeriesPointToJSON,
    AnalyticsTimeSeriesPointToJSONTyped,
} from './AnalyticsTimeSeriesPoint';
import type { AnalyticsIntegration } from './AnalyticsIntegration';
import {
    AnalyticsIntegrationFromJSON,
    AnalyticsIntegrationFromJSONTyped,
    AnalyticsIntegrationToJSON,
    AnalyticsIntegrationToJSONTyped,
} from './AnalyticsIntegration';
import type { AnalyticsRateSchedule } from './AnalyticsRateSchedule';
import {
    AnalyticsRateScheduleFromJSON,
    AnalyticsRateScheduleFromJSONTyped,
    AnalyticsRateScheduleToJSON,
    AnalyticsRateScheduleToJSONTyped,
} from './AnalyticsRateSchedule';

/**
 * 
 * @export
 * @interface AnalyticsPower
 */
export interface AnalyticsPower {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    battery_kwh_168h?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    battery_kwh_24h?: number;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsPower
     */
    battery_series_168h?: Array<AnalyticsTimeSeriesPoint>;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsPower
     */
    battery_series_24h?: Array<AnalyticsTimeSeriesPoint>;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    grid_kwh_168h?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    grid_kwh_24h?: number;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsPower
     */
    grid_series_168h?: Array<AnalyticsTimeSeriesPoint>;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsPower
     */
    grid_series_24h?: Array<AnalyticsTimeSeriesPoint>;
    /**
     * 
     * @type {Array<AnalyticsIntegration>}
     * @memberof AnalyticsPower
     */
    integrations?: Array<AnalyticsIntegration>;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    kwh_168h: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    kwh_24h: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    live_battery_kw?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    live_grid_kw: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    live_kw: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    live_solar_kw: number;
    /**
     * 
     * @type {AnalyticsRateSchedule}
     * @memberof AnalyticsPower
     */
    rate_schedule: AnalyticsRateSchedule;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsPower
     */
    series_168h: Array<AnalyticsTimeSeriesPoint>;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsPower
     */
    series_24h: Array<AnalyticsTimeSeriesPoint>;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    solar_kwh_168h?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPower
     */
    solar_kwh_24h?: number;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsPower
     */
    solar_series_168h?: Array<AnalyticsTimeSeriesPoint>;
    /**
     * 
     * @type {Array<AnalyticsTimeSeriesPoint>}
     * @memberof AnalyticsPower
     */
    solar_series_24h?: Array<AnalyticsTimeSeriesPoint>;
}

/**
 * Check if a given object implements the AnalyticsPower interface.
 */
export function instanceOfAnalyticsPower(value: object): value is AnalyticsPower {
    if (!('kwh_168h' in value) || value['kwh_168h'] === undefined) return false;
    if (!('kwh_24h' in value) || value['kwh_24h'] === undefined) return false;
    if (!('live_grid_kw' in value) || value['live_grid_kw'] === undefined) return false;
    if (!('live_kw' in value) || value['live_kw'] === undefined) return false;
    if (!('live_solar_kw' in value) || value['live_solar_kw'] === undefined) return false;
    if (!('rate_schedule' in value) || value['rate_schedule'] === undefined) return false;
    if (!('series_168h' in value) || value['series_168h'] === undefined) return false;
    if (!('series_24h' in value) || value['series_24h'] === undefined) return false;
    return true;
}

export function AnalyticsPowerFromJSON(json: any): AnalyticsPower {
    return AnalyticsPowerFromJSONTyped(json, false);
}

export function AnalyticsPowerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsPower {
    if (json == null) {
        return json;
    }
    return {
        
        'battery_kwh_168h': json['battery_kwh_168h'] == null ? undefined : json['battery_kwh_168h'],
        'battery_kwh_24h': json['battery_kwh_24h'] == null ? undefined : json['battery_kwh_24h'],
        'battery_series_168h': json['battery_series_168h'] == null ? undefined : ((json['battery_series_168h'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
        'battery_series_24h': json['battery_series_24h'] == null ? undefined : ((json['battery_series_24h'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
        'grid_kwh_168h': json['grid_kwh_168h'] == null ? undefined : json['grid_kwh_168h'],
        'grid_kwh_24h': json['grid_kwh_24h'] == null ? undefined : json['grid_kwh_24h'],
        'grid_series_168h': json['grid_series_168h'] == null ? undefined : ((json['grid_series_168h'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
        'grid_series_24h': json['grid_series_24h'] == null ? undefined : ((json['grid_series_24h'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
        'integrations': json['integrations'] == null ? undefined : ((json['integrations'] as Array<any>).map(AnalyticsIntegrationFromJSON)),
        'kwh_168h': json['kwh_168h'],
        'kwh_24h': json['kwh_24h'],
        'live_battery_kw': json['live_battery_kw'] == null ? undefined : json['live_battery_kw'],
        'live_grid_kw': json['live_grid_kw'],
        'live_kw': json['live_kw'],
        'live_solar_kw': json['live_solar_kw'],
        'rate_schedule': AnalyticsRateScheduleFromJSON(json['rate_schedule']),
        'series_168h': ((json['series_168h'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
        'series_24h': ((json['series_24h'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
        'solar_kwh_168h': json['solar_kwh_168h'] == null ? undefined : json['solar_kwh_168h'],
        'solar_kwh_24h': json['solar_kwh_24h'] == null ? undefined : json['solar_kwh_24h'],
        'solar_series_168h': json['solar_series_168h'] == null ? undefined : ((json['solar_series_168h'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
        'solar_series_24h': json['solar_series_24h'] == null ? undefined : ((json['solar_series_24h'] as Array<any>).map(AnalyticsTimeSeriesPointFromJSON)),
    };
}

export function AnalyticsPowerToJSON(json: any): AnalyticsPower {
    return AnalyticsPowerToJSONTyped(json, false);
}

export function AnalyticsPowerToJSONTyped(value?: AnalyticsPower | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'battery_kwh_168h': value['battery_kwh_168h'],
        'battery_kwh_24h': value['battery_kwh_24h'],
        'battery_series_168h': value['battery_series_168h'] == null ? undefined : ((value['battery_series_168h'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
        'battery_series_24h': value['battery_series_24h'] == null ? undefined : ((value['battery_series_24h'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
        'grid_kwh_168h': value['grid_kwh_168h'],
        'grid_kwh_24h': value['grid_kwh_24h'],
        'grid_series_168h': value['grid_series_168h'] == null ? undefined : ((value['grid_series_168h'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
        'grid_series_24h': value['grid_series_24h'] == null ? undefined : ((value['grid_series_24h'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
        'integrations': value['integrations'] == null ? undefined : ((value['integrations'] as Array<any>).map(AnalyticsIntegrationToJSON)),
        'kwh_168h': value['kwh_168h'],
        'kwh_24h': value['kwh_24h'],
        'live_battery_kw': value['live_battery_kw'],
        'live_grid_kw': value['live_grid_kw'],
        'live_kw': value['live_kw'],
        'live_solar_kw': value['live_solar_kw'],
        'rate_schedule': AnalyticsRateScheduleToJSON(value['rate_schedule']),
        'series_168h': ((value['series_168h'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
        'series_24h': ((value['series_24h'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
        'solar_kwh_168h': value['solar_kwh_168h'],
        'solar_kwh_24h': value['solar_kwh_24h'],
        'solar_series_168h': value['solar_series_168h'] == null ? undefined : ((value['solar_series_168h'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
        'solar_series_24h': value['solar_series_24h'] == null ? undefined : ((value['solar_series_24h'] as Array<any>).map(AnalyticsTimeSeriesPointToJSON)),
    };
}

