/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsFeedStatusEntry } from './AnalyticsFeedStatusEntry';
import {
    AnalyticsFeedStatusEntryFromJSON,
    AnalyticsFeedStatusEntryFromJSONTyped,
    AnalyticsFeedStatusEntryToJSON,
    AnalyticsFeedStatusEntryToJSONTyped,
} from './AnalyticsFeedStatusEntry';

/**
 * 
 * @export
 * @interface AnalyticsStatus
 */
export interface AnalyticsStatus {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    alarms_last_168h: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    battery_runtime_hours: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    battery_soc: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    current_load_kw?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    estimated_runtime_hours?: number;
    /**
     * 
     * @type {{ [key: string]: AnalyticsFeedStatusEntry; }}
     * @memberof AnalyticsStatus
     */
    feeds?: { [key: string]: AnalyticsFeedStatusEntry; };
    /**
     * 
     * @type {string}
     * @memberof AnalyticsStatus
     */
    last_updated?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    nodes_offline: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    nodes_online: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    remote_nodes_offline?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    remote_nodes_online?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    solar_kw: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    storage_capacity_kwh?: number;
}

/**
 * Check if a given object implements the AnalyticsStatus interface.
 */
export function instanceOfAnalyticsStatus(value: object): value is AnalyticsStatus {
    if (!('alarms_last_168h' in value) || value['alarms_last_168h'] === undefined) return false;
    if (!('battery_runtime_hours' in value) || value['battery_runtime_hours'] === undefined) return false;
    if (!('battery_soc' in value) || value['battery_soc'] === undefined) return false;
    if (!('nodes_offline' in value) || value['nodes_offline'] === undefined) return false;
    if (!('nodes_online' in value) || value['nodes_online'] === undefined) return false;
    if (!('solar_kw' in value) || value['solar_kw'] === undefined) return false;
    return true;
}

export function AnalyticsStatusFromJSON(json: any): AnalyticsStatus {
    return AnalyticsStatusFromJSONTyped(json, false);
}

export function AnalyticsStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'alarms_last_168h': json['alarms_last_168h'],
        'battery_runtime_hours': json['battery_runtime_hours'],
        'battery_soc': json['battery_soc'],
        'current_load_kw': json['current_load_kw'] == null ? undefined : json['current_load_kw'],
        'estimated_runtime_hours': json['estimated_runtime_hours'] == null ? undefined : json['estimated_runtime_hours'],
        'feeds': json['feeds'] == null ? undefined : (mapValues(json['feeds'], AnalyticsFeedStatusEntryFromJSON)),
        'last_updated': json['last_updated'] == null ? undefined : json['last_updated'],
        'nodes_offline': json['nodes_offline'],
        'nodes_online': json['nodes_online'],
        'remote_nodes_offline': json['remote_nodes_offline'] == null ? undefined : json['remote_nodes_offline'],
        'remote_nodes_online': json['remote_nodes_online'] == null ? undefined : json['remote_nodes_online'],
        'solar_kw': json['solar_kw'],
        'storage_capacity_kwh': json['storage_capacity_kwh'] == null ? undefined : json['storage_capacity_kwh'],
    };
}

export function AnalyticsStatusToJSON(json: any): AnalyticsStatus {
    return AnalyticsStatusToJSONTyped(json, false);
}

export function AnalyticsStatusToJSONTyped(value?: AnalyticsStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alarms_last_168h': value['alarms_last_168h'],
        'battery_runtime_hours': value['battery_runtime_hours'],
        'battery_soc': value['battery_soc'],
        'current_load_kw': value['current_load_kw'],
        'estimated_runtime_hours': value['estimated_runtime_hours'],
        'feeds': value['feeds'] == null ? undefined : (mapValues(value['feeds'], AnalyticsFeedStatusEntryToJSON)),
        'last_updated': value['last_updated'],
        'nodes_offline': value['nodes_offline'],
        'nodes_online': value['nodes_online'],
        'remote_nodes_offline': value['remote_nodes_offline'],
        'remote_nodes_online': value['remote_nodes_online'],
        'solar_kw': value['solar_kw'],
        'storage_capacity_kwh': value['storage_capacity_kwh'],
    };
}

