/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalysisJobPublic } from './AnalysisJobPublic';
import {
    AnalysisJobPublicFromJSON,
    AnalysisJobPublicFromJSONTyped,
    AnalysisJobPublicToJSON,
    AnalysisJobPublicToJSONTyped,
} from './AnalysisJobPublic';

/**
 * 
 * @export
 * @interface AnalysisJobCancelResponse
 */
export interface AnalysisJobCancelResponse {
    /**
     * 
     * @type {AnalysisJobPublic}
     * @memberof AnalysisJobCancelResponse
     */
    job: AnalysisJobPublic;
}

/**
 * Check if a given object implements the AnalysisJobCancelResponse interface.
 */
export function instanceOfAnalysisJobCancelResponse(value: object): value is AnalysisJobCancelResponse {
    if (!('job' in value) || value['job'] === undefined) return false;
    return true;
}

export function AnalysisJobCancelResponseFromJSON(json: any): AnalysisJobCancelResponse {
    return AnalysisJobCancelResponseFromJSONTyped(json, false);
}

export function AnalysisJobCancelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalysisJobCancelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'job': AnalysisJobPublicFromJSON(json['job']),
    };
}

export function AnalysisJobCancelResponseToJSON(json: any): AnalysisJobCancelResponse {
    return AnalysisJobCancelResponseToJSONTyped(json, false);
}

export function AnalysisJobCancelResponseToJSONTyped(value?: AnalysisJobCancelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job': AnalysisJobPublicToJSON(value['job']),
    };
}

