/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsTimeSeriesPoint
 */
export interface AnalyticsTimeSeriesPoint {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsTimeSeriesPoint
     */
    timestamp: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsTimeSeriesPoint
     */
    value: number;
}

/**
 * Check if a given object implements the AnalyticsTimeSeriesPoint interface.
 */
export function instanceOfAnalyticsTimeSeriesPoint(value: object): value is AnalyticsTimeSeriesPoint {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AnalyticsTimeSeriesPointFromJSON(json: any): AnalyticsTimeSeriesPoint {
    return AnalyticsTimeSeriesPointFromJSONTyped(json, false);
}

export function AnalyticsTimeSeriesPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsTimeSeriesPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'value': json['value'],
    };
}

export function AnalyticsTimeSeriesPointToJSON(json: any): AnalyticsTimeSeriesPoint {
    return AnalyticsTimeSeriesPointToJSONTyped(json, false);
}

export function AnalyticsTimeSeriesPointToJSONTyped(value?: AnalyticsTimeSeriesPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'value': value['value'],
    };
}

