/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsFeedStatusEntry } from './AnalyticsFeedStatusEntry';
import {
    AnalyticsFeedStatusEntryFromJSON,
    AnalyticsFeedStatusEntryFromJSONTyped,
    AnalyticsFeedStatusEntryToJSON,
    AnalyticsFeedStatusEntryToJSONTyped,
} from './AnalyticsFeedStatusEntry';
import type { AnalyticsFeedHistoryEntry } from './AnalyticsFeedHistoryEntry';
import {
    AnalyticsFeedHistoryEntryFromJSON,
    AnalyticsFeedHistoryEntryFromJSONTyped,
    AnalyticsFeedHistoryEntryToJSON,
    AnalyticsFeedHistoryEntryToJSONTyped,
} from './AnalyticsFeedHistoryEntry';

/**
 * 
 * @export
 * @interface AnalyticsFeedStatusResponse
 */
export interface AnalyticsFeedStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AnalyticsFeedStatusResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {{ [key: string]: AnalyticsFeedStatusEntry; }}
     * @memberof AnalyticsFeedStatusResponse
     */
    feeds?: { [key: string]: AnalyticsFeedStatusEntry; };
    /**
     * 
     * @type {Array<AnalyticsFeedHistoryEntry>}
     * @memberof AnalyticsFeedStatusResponse
     */
    history?: Array<AnalyticsFeedHistoryEntry>;
}

/**
 * Check if a given object implements the AnalyticsFeedStatusResponse interface.
 */
export function instanceOfAnalyticsFeedStatusResponse(value: object): value is AnalyticsFeedStatusResponse {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function AnalyticsFeedStatusResponseFromJSON(json: any): AnalyticsFeedStatusResponse {
    return AnalyticsFeedStatusResponseFromJSONTyped(json, false);
}

export function AnalyticsFeedStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsFeedStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'feeds': json['feeds'] == null ? undefined : (mapValues(json['feeds'], AnalyticsFeedStatusEntryFromJSON)),
        'history': json['history'] == null ? undefined : ((json['history'] as Array<any>).map(AnalyticsFeedHistoryEntryFromJSON)),
    };
}

export function AnalyticsFeedStatusResponseToJSON(json: any): AnalyticsFeedStatusResponse {
    return AnalyticsFeedStatusResponseToJSONTyped(json, false);
}

export function AnalyticsFeedStatusResponseToJSONTyped(value?: AnalyticsFeedStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'feeds': value['feeds'] == null ? undefined : (mapValues(value['feeds'], AnalyticsFeedStatusEntryToJSON)),
        'history': value['history'] == null ? undefined : ((value['history'] as Array<any>).map(AnalyticsFeedHistoryEntryToJSON)),
    };
}

