/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsFeedStatusEntry
 */
export interface AnalyticsFeedStatusEntry {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsFeedStatusEntry
     */
    details?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsFeedStatusEntry
     */
    last_seen?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsFeedStatusEntry
     */
    status?: string | null;
}

/**
 * Check if a given object implements the AnalyticsFeedStatusEntry interface.
 */
export function instanceOfAnalyticsFeedStatusEntry(value: object): value is AnalyticsFeedStatusEntry {
    return true;
}

export function AnalyticsFeedStatusEntryFromJSON(json: any): AnalyticsFeedStatusEntry {
    return AnalyticsFeedStatusEntryFromJSONTyped(json, false);
}

export function AnalyticsFeedStatusEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsFeedStatusEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'] == null ? undefined : json['details'],
        'last_seen': json['last_seen'] == null ? undefined : json['last_seen'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AnalyticsFeedStatusEntryToJSON(json: any): AnalyticsFeedStatusEntry {
    return AnalyticsFeedStatusEntryToJSONTyped(json, false);
}

export function AnalyticsFeedStatusEntryToJSONTyped(value?: AnalyticsFeedStatusEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': value['details'],
        'last_seen': value['last_seen'],
        'status': value['status'],
    };
}

