/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnotationResponse
 */
export interface AnnotationResponse {
    /**
     * 
     * @type {any}
     * @memberof AnnotationResponse
     */
    chart_state: any | null;
    /**
     * 
     * @type {string}
     * @memberof AnnotationResponse
     */
    created_at: string;
    /**
     * 
     * @type {string}
     * @memberof AnnotationResponse
     */
    created_by?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnnotationResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AnnotationResponse
     */
    label?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnnotationResponse
     */
    sensor_ids?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AnnotationResponse
     */
    time_end?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnnotationResponse
     */
    time_start?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnnotationResponse
     */
    updated_at: string;
}

/**
 * Check if a given object implements the AnnotationResponse interface.
 */
export function instanceOfAnnotationResponse(value: object): value is AnnotationResponse {
    if (!('chart_state' in value) || value['chart_state'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function AnnotationResponseFromJSON(json: any): AnnotationResponse {
    return AnnotationResponseFromJSONTyped(json, false);
}

export function AnnotationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnotationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chart_state': json['chart_state'],
        'created_at': json['created_at'],
        'created_by': json['created_by'] == null ? undefined : json['created_by'],
        'id': json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'sensor_ids': json['sensor_ids'] == null ? undefined : json['sensor_ids'],
        'time_end': json['time_end'] == null ? undefined : json['time_end'],
        'time_start': json['time_start'] == null ? undefined : json['time_start'],
        'updated_at': json['updated_at'],
    };
}

export function AnnotationResponseToJSON(json: any): AnnotationResponse {
    return AnnotationResponseToJSONTyped(json, false);
}

export function AnnotationResponseToJSONTyped(value?: AnnotationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chart_state': value['chart_state'],
        'created_at': value['created_at'],
        'created_by': value['created_by'],
        'id': value['id'],
        'label': value['label'],
        'sensor_ids': value['sensor_ids'],
        'time_end': value['time_end'],
        'time_start': value['time_start'],
        'updated_at': value['updated_at'],
    };
}

