/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiTokenInfo
 */
export interface ApiTokenInfo {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiTokenInfo
     */
    capabilities: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApiTokenInfo
     */
    created_at: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTokenInfo
     */
    expires_at?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiTokenInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTokenInfo
     */
    last_used_at?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiTokenInfo
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiTokenInfo
     */
    revoked_at?: string | null;
}

/**
 * Check if a given object implements the ApiTokenInfo interface.
 */
export function instanceOfApiTokenInfo(value: object): value is ApiTokenInfo {
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ApiTokenInfoFromJSON(json: any): ApiTokenInfo {
    return ApiTokenInfoFromJSONTyped(json, false);
}

export function ApiTokenInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTokenInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'capabilities': json['capabilities'],
        'created_at': json['created_at'],
        'expires_at': json['expires_at'] == null ? undefined : json['expires_at'],
        'id': json['id'],
        'last_used_at': json['last_used_at'] == null ? undefined : json['last_used_at'],
        'name': json['name'] == null ? undefined : json['name'],
        'revoked_at': json['revoked_at'] == null ? undefined : json['revoked_at'],
    };
}

export function ApiTokenInfoToJSON(json: any): ApiTokenInfo {
    return ApiTokenInfoToJSONTyped(json, false);
}

export function ApiTokenInfoToJSONTyped(value?: ApiTokenInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capabilities': value['capabilities'],
        'created_at': value['created_at'],
        'expires_at': value['expires_at'],
        'id': value['id'],
        'last_used_at': value['last_used_at'],
        'name': value['name'],
        'revoked_at': value['revoked_at'],
    };
}

