/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeSensorDraft } from './NodeSensorDraft';
import {
    NodeSensorDraftFromJSON,
    NodeSensorDraftFromJSONTyped,
    NodeSensorDraftToJSON,
    NodeSensorDraftToJSONTyped,
} from './NodeSensorDraft';

/**
 * 
 * @export
 * @interface ApplyNodeSensorsConfigResponse
 */
export interface ApplyNodeSensorsConfigResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplyNodeSensorsConfigResponse
     */
    deleted_sensor_ids: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApplyNodeSensorsConfigResponse
     */
    node_agent_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplyNodeSensorsConfigResponse
     */
    node_id: string;
    /**
     * 
     * @type {Array<NodeSensorDraft>}
     * @memberof ApplyNodeSensorsConfigResponse
     */
    sensors: Array<NodeSensorDraft>;
    /**
     * 
     * @type {string}
     * @memberof ApplyNodeSensorsConfigResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ApplyNodeSensorsConfigResponse
     */
    warning?: string | null;
}

/**
 * Check if a given object implements the ApplyNodeSensorsConfigResponse interface.
 */
export function instanceOfApplyNodeSensorsConfigResponse(value: object): value is ApplyNodeSensorsConfigResponse {
    if (!('deleted_sensor_ids' in value) || value['deleted_sensor_ids'] === undefined) return false;
    if (!('node_id' in value) || value['node_id'] === undefined) return false;
    if (!('sensors' in value) || value['sensors'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ApplyNodeSensorsConfigResponseFromJSON(json: any): ApplyNodeSensorsConfigResponse {
    return ApplyNodeSensorsConfigResponseFromJSONTyped(json, false);
}

export function ApplyNodeSensorsConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyNodeSensorsConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted_sensor_ids': json['deleted_sensor_ids'],
        'node_agent_url': json['node_agent_url'] == null ? undefined : json['node_agent_url'],
        'node_id': json['node_id'],
        'sensors': ((json['sensors'] as Array<any>).map(NodeSensorDraftFromJSON)),
        'status': json['status'],
        'warning': json['warning'] == null ? undefined : json['warning'],
    };
}

export function ApplyNodeSensorsConfigResponseToJSON(json: any): ApplyNodeSensorsConfigResponse {
    return ApplyNodeSensorsConfigResponseToJSONTyped(json, false);
}

export function ApplyNodeSensorsConfigResponseToJSONTyped(value?: ApplyNodeSensorsConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted_sensor_ids': value['deleted_sensor_ids'],
        'node_agent_url': value['node_agent_url'],
        'node_id': value['node_id'],
        'sensors': ((value['sensors'] as Array<any>).map(NodeSensorDraftToJSON)),
        'status': value['status'],
        'warning': value['warning'],
    };
}

