/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BatteryChemistry = {
    lifepo4: 'lifepo4',
    lead_acid: 'lead_acid'
} as const;
export type BatteryChemistry = typeof BatteryChemistry[keyof typeof BatteryChemistry];


export function instanceOfBatteryChemistry(value: any): boolean {
    for (const key in BatteryChemistry) {
        if (Object.prototype.hasOwnProperty.call(BatteryChemistry, key)) {
            if (BatteryChemistry[key as keyof typeof BatteryChemistry] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BatteryChemistryFromJSON(json: any): BatteryChemistry {
    return BatteryChemistryFromJSONTyped(json, false);
}

export function BatteryChemistryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatteryChemistry {
    return json as BatteryChemistry;
}

export function BatteryChemistryToJSON(value?: BatteryChemistry | null): any {
    return value as any;
}

export function BatteryChemistryToJSONTyped(value: any, ignoreDiscriminator: boolean): BatteryChemistry {
    return value as BatteryChemistry;
}

