/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkAcknowledgeRequest
 */
export interface BulkAcknowledgeRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkAcknowledgeRequest
     */
    event_ids: Array<string>;
}

/**
 * Check if a given object implements the BulkAcknowledgeRequest interface.
 */
export function instanceOfBulkAcknowledgeRequest(value: object): value is BulkAcknowledgeRequest {
    if (!('event_ids' in value) || value['event_ids'] === undefined) return false;
    return true;
}

export function BulkAcknowledgeRequestFromJSON(json: any): BulkAcknowledgeRequest {
    return BulkAcknowledgeRequestFromJSONTyped(json, false);
}

export function BulkAcknowledgeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkAcknowledgeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'event_ids': json['event_ids'],
    };
}

export function BulkAcknowledgeRequestToJSON(json: any): BulkAcknowledgeRequest {
    return BulkAcknowledgeRequestToJSONTyped(json, false);
}

export function BulkAcknowledgeRequestToJSONTyped(value?: BulkAcknowledgeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_ids': value['event_ids'],
    };
}

