/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkAcknowledgeResponse
 */
export interface BulkAcknowledgeResponse {
    /**
     * 
     * @type {number}
     * @memberof BulkAcknowledgeResponse
     */
    acknowledged: number;
}

/**
 * Check if a given object implements the BulkAcknowledgeResponse interface.
 */
export function instanceOfBulkAcknowledgeResponse(value: object): value is BulkAcknowledgeResponse {
    if (!('acknowledged' in value) || value['acknowledged'] === undefined) return false;
    return true;
}

export function BulkAcknowledgeResponseFromJSON(json: any): BulkAcknowledgeResponse {
    return BulkAcknowledgeResponseFromJSONTyped(json, false);
}

export function BulkAcknowledgeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkAcknowledgeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'acknowledged': json['acknowledged'],
    };
}

export function BulkAcknowledgeResponseToJSON(json: any): BulkAcknowledgeResponse {
    return BulkAcknowledgeResponseToJSONTyped(json, false);
}

export function BulkAcknowledgeResponseToJSONTyped(value?: BulkAcknowledgeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acknowledged': value['acknowledged'],
    };
}

