/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloudAccessUpdateRequest
 */
export interface CloudAccessUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof CloudAccessUpdateRequest
     */
    cloud_server_base_url?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CloudAccessUpdateRequest
     */
    sync_enabled?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof CloudAccessUpdateRequest
     */
    sync_interval_seconds?: number | null;
}

/**
 * Check if a given object implements the CloudAccessUpdateRequest interface.
 */
export function instanceOfCloudAccessUpdateRequest(value: object): value is CloudAccessUpdateRequest {
    return true;
}

export function CloudAccessUpdateRequestFromJSON(json: any): CloudAccessUpdateRequest {
    return CloudAccessUpdateRequestFromJSONTyped(json, false);
}

export function CloudAccessUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudAccessUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cloud_server_base_url': json['cloud_server_base_url'] == null ? undefined : json['cloud_server_base_url'],
        'sync_enabled': json['sync_enabled'] == null ? undefined : json['sync_enabled'],
        'sync_interval_seconds': json['sync_interval_seconds'] == null ? undefined : json['sync_interval_seconds'],
    };
}

export function CloudAccessUpdateRequestToJSON(json: any): CloudAccessUpdateRequest {
    return CloudAccessUpdateRequestToJSONTyped(json, false);
}

export function CloudAccessUpdateRequestToJSONTyped(value?: CloudAccessUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cloud_server_base_url': value['cloud_server_base_url'],
        'sync_enabled': value['sync_enabled'],
        'sync_interval_seconds': value['sync_interval_seconds'],
    };
}

