/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionResponse
 */
export interface ConnectionResponse {
    /**
     * 
     * @type {string}
     * @memberof ConnectionResponse
     */
    cloud_address: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionResponse
     */
    last_switch?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConnectionResponse
     */
    local_address: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionResponse
     */
    mode: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionResponse
     */
    timezone: string;
}

/**
 * Check if a given object implements the ConnectionResponse interface.
 */
export function instanceOfConnectionResponse(value: object): value is ConnectionResponse {
    if (!('cloud_address' in value) || value['cloud_address'] === undefined) return false;
    if (!('local_address' in value) || value['local_address'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    return true;
}

export function ConnectionResponseFromJSON(json: any): ConnectionResponse {
    return ConnectionResponseFromJSONTyped(json, false);
}

export function ConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cloud_address': json['cloud_address'],
        'last_switch': json['last_switch'] == null ? undefined : json['last_switch'],
        'local_address': json['local_address'],
        'mode': json['mode'],
        'status': json['status'],
        'timezone': json['timezone'],
    };
}

export function ConnectionResponseToJSON(json: any): ConnectionResponse {
    return ConnectionResponseToJSONTyped(json, false);
}

export function ConnectionResponseToJSONTyped(value?: ConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cloud_address': value['cloud_address'],
        'last_switch': value['last_switch'],
        'local_address': value['local_address'],
        'mode': value['mode'],
        'status': value['status'],
        'timezone': value['timezone'],
    };
}

