/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionUpdate
 */
export interface ConnectionUpdate {
    /**
     * 
     * @type {string}
     * @memberof ConnectionUpdate
     */
    cloud_address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConnectionUpdate
     */
    local_address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConnectionUpdate
     */
    mode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConnectionUpdate
     */
    status?: string | null;
}

/**
 * Check if a given object implements the ConnectionUpdate interface.
 */
export function instanceOfConnectionUpdate(value: object): value is ConnectionUpdate {
    return true;
}

export function ConnectionUpdateFromJSON(json: any): ConnectionUpdate {
    return ConnectionUpdateFromJSONTyped(json, false);
}

export function ConnectionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'cloud_address': json['cloud_address'] == null ? undefined : json['cloud_address'],
        'local_address': json['local_address'] == null ? undefined : json['local_address'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ConnectionUpdateToJSON(json: any): ConnectionUpdate {
    return ConnectionUpdateToJSONTyped(json, false);
}

export function ConnectionUpdateToJSONTyped(value?: ConnectionUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cloud_address': value['cloud_address'],
        'local_address': value['local_address'],
        'mode': value['mode'],
        'status': value['status'],
    };
}

