/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllerRuntimeConfigPatchRequest
 */
export interface ControllerRuntimeConfigPatchRequest {
    /**
     * 
     * @type {number}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    analytics_feed_poll_interval_seconds?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    enable_analytics_feeds?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    enable_forecast_ingestion?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    forecast_poll_interval_seconds?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    mqtt_password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    mqtt_username?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    offline_threshold_seconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    schedule_poll_interval_seconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    sidecar_batch_size?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    sidecar_enable_mqtt_listener?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    sidecar_flush_interval_ms?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    sidecar_max_queue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    sidecar_mqtt_keepalive_secs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    sidecar_mqtt_topic_prefix?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ControllerRuntimeConfigPatchRequest
     */
    sidecar_status_poll_interval_ms?: number | null;
}

/**
 * Check if a given object implements the ControllerRuntimeConfigPatchRequest interface.
 */
export function instanceOfControllerRuntimeConfigPatchRequest(value: object): value is ControllerRuntimeConfigPatchRequest {
    return true;
}

export function ControllerRuntimeConfigPatchRequestFromJSON(json: any): ControllerRuntimeConfigPatchRequest {
    return ControllerRuntimeConfigPatchRequestFromJSONTyped(json, false);
}

export function ControllerRuntimeConfigPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllerRuntimeConfigPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'analytics_feed_poll_interval_seconds': json['analytics_feed_poll_interval_seconds'] == null ? undefined : json['analytics_feed_poll_interval_seconds'],
        'enable_analytics_feeds': json['enable_analytics_feeds'] == null ? undefined : json['enable_analytics_feeds'],
        'enable_forecast_ingestion': json['enable_forecast_ingestion'] == null ? undefined : json['enable_forecast_ingestion'],
        'forecast_poll_interval_seconds': json['forecast_poll_interval_seconds'] == null ? undefined : json['forecast_poll_interval_seconds'],
        'mqtt_password': json['mqtt_password'] == null ? undefined : json['mqtt_password'],
        'mqtt_username': json['mqtt_username'] == null ? undefined : json['mqtt_username'],
        'offline_threshold_seconds': json['offline_threshold_seconds'] == null ? undefined : json['offline_threshold_seconds'],
        'schedule_poll_interval_seconds': json['schedule_poll_interval_seconds'] == null ? undefined : json['schedule_poll_interval_seconds'],
        'sidecar_batch_size': json['sidecar_batch_size'] == null ? undefined : json['sidecar_batch_size'],
        'sidecar_enable_mqtt_listener': json['sidecar_enable_mqtt_listener'] == null ? undefined : json['sidecar_enable_mqtt_listener'],
        'sidecar_flush_interval_ms': json['sidecar_flush_interval_ms'] == null ? undefined : json['sidecar_flush_interval_ms'],
        'sidecar_max_queue': json['sidecar_max_queue'] == null ? undefined : json['sidecar_max_queue'],
        'sidecar_mqtt_keepalive_secs': json['sidecar_mqtt_keepalive_secs'] == null ? undefined : json['sidecar_mqtt_keepalive_secs'],
        'sidecar_mqtt_topic_prefix': json['sidecar_mqtt_topic_prefix'] == null ? undefined : json['sidecar_mqtt_topic_prefix'],
        'sidecar_status_poll_interval_ms': json['sidecar_status_poll_interval_ms'] == null ? undefined : json['sidecar_status_poll_interval_ms'],
    };
}

export function ControllerRuntimeConfigPatchRequestToJSON(json: any): ControllerRuntimeConfigPatchRequest {
    return ControllerRuntimeConfigPatchRequestToJSONTyped(json, false);
}

export function ControllerRuntimeConfigPatchRequestToJSONTyped(value?: ControllerRuntimeConfigPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'analytics_feed_poll_interval_seconds': value['analytics_feed_poll_interval_seconds'],
        'enable_analytics_feeds': value['enable_analytics_feeds'],
        'enable_forecast_ingestion': value['enable_forecast_ingestion'],
        'forecast_poll_interval_seconds': value['forecast_poll_interval_seconds'],
        'mqtt_password': value['mqtt_password'],
        'mqtt_username': value['mqtt_username'],
        'offline_threshold_seconds': value['offline_threshold_seconds'],
        'schedule_poll_interval_seconds': value['schedule_poll_interval_seconds'],
        'sidecar_batch_size': value['sidecar_batch_size'],
        'sidecar_enable_mqtt_listener': value['sidecar_enable_mqtt_listener'],
        'sidecar_flush_interval_ms': value['sidecar_flush_interval_ms'],
        'sidecar_max_queue': value['sidecar_max_queue'],
        'sidecar_mqtt_keepalive_secs': value['sidecar_mqtt_keepalive_secs'],
        'sidecar_mqtt_topic_prefix': value['sidecar_mqtt_topic_prefix'],
        'sidecar_status_poll_interval_ms': value['sidecar_status_poll_interval_ms'],
    };
}

