/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DevActivityHeartbeatRequest
 */
export interface DevActivityHeartbeatRequest {
    /**
     * 
     * @type {string}
     * @memberof DevActivityHeartbeatRequest
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DevActivityHeartbeatRequest
     */
    source?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DevActivityHeartbeatRequest
     */
    ttl_seconds?: number | null;
}

/**
 * Check if a given object implements the DevActivityHeartbeatRequest interface.
 */
export function instanceOfDevActivityHeartbeatRequest(value: object): value is DevActivityHeartbeatRequest {
    return true;
}

export function DevActivityHeartbeatRequestFromJSON(json: any): DevActivityHeartbeatRequest {
    return DevActivityHeartbeatRequestFromJSONTyped(json, false);
}

export function DevActivityHeartbeatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevActivityHeartbeatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'source': json['source'] == null ? undefined : json['source'],
        'ttl_seconds': json['ttl_seconds'] == null ? undefined : json['ttl_seconds'],
    };
}

export function DevActivityHeartbeatRequestToJSON(json: any): DevActivityHeartbeatRequest {
    return DevActivityHeartbeatRequestToJSONTyped(json, false);
}

export function DevActivityHeartbeatRequestToJSONTyped(value?: DevActivityHeartbeatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'source': value['source'],
        'ttl_seconds': value['ttl_seconds'],
    };
}

