/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DevicePoint
 */
export interface DevicePoint {
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    bacnet_object?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    data_type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    json_pointer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    metric: string;
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    oid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    protocol: string;
    /**
     * 
     * @type {number}
     * @memberof DevicePoint
     */
    register?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DevicePoint
     */
    scale?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    sensor_type: string;
    /**
     * 
     * @type {string}
     * @memberof DevicePoint
     */
    unit: string;
}

/**
 * Check if a given object implements the DevicePoint interface.
 */
export function instanceOfDevicePoint(value: object): value is DevicePoint {
    if (!('metric' in value) || value['metric'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('protocol' in value) || value['protocol'] === undefined) return false;
    if (!('sensor_type' in value) || value['sensor_type'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function DevicePointFromJSON(json: any): DevicePoint {
    return DevicePointFromJSONTyped(json, false);
}

export function DevicePointFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevicePoint {
    if (json == null) {
        return json;
    }
    return {
        
        'bacnet_object': json['bacnet_object'] == null ? undefined : json['bacnet_object'],
        'data_type': json['data_type'] == null ? undefined : json['data_type'],
        'json_pointer': json['json_pointer'] == null ? undefined : json['json_pointer'],
        'metric': json['metric'],
        'name': json['name'],
        'oid': json['oid'] == null ? undefined : json['oid'],
        'path': json['path'] == null ? undefined : json['path'],
        'protocol': json['protocol'],
        'register': json['register'] == null ? undefined : json['register'],
        'scale': json['scale'] == null ? undefined : json['scale'],
        'sensor_type': json['sensor_type'],
        'unit': json['unit'],
    };
}

export function DevicePointToJSON(json: any): DevicePoint {
    return DevicePointToJSONTyped(json, false);
}

export function DevicePointToJSONTyped(value?: DevicePoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bacnet_object': value['bacnet_object'],
        'data_type': value['data_type'],
        'json_pointer': value['json_pointer'],
        'metric': value['metric'],
        'name': value['name'],
        'oid': value['oid'],
        'path': value['path'],
        'protocol': value['protocol'],
        'register': value['register'],
        'scale': value['scale'],
        'sensor_type': value['sensor_type'],
        'unit': value['unit'],
    };
}

