/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceVendor } from './DeviceVendor';
import {
    DeviceVendorFromJSON,
    DeviceVendorFromJSONTyped,
    DeviceVendorToJSON,
    DeviceVendorToJSONTyped,
} from './DeviceVendor';

/**
 * 
 * @export
 * @interface DeviceCatalog
 */
export interface DeviceCatalog {
    /**
     * 
     * @type {Array<DeviceVendor>}
     * @memberof DeviceCatalog
     */
    vendors: Array<DeviceVendor>;
    /**
     * 
     * @type {number}
     * @memberof DeviceCatalog
     */
    version: number;
}

/**
 * Check if a given object implements the DeviceCatalog interface.
 */
export function instanceOfDeviceCatalog(value: object): value is DeviceCatalog {
    if (!('vendors' in value) || value['vendors'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function DeviceCatalogFromJSON(json: any): DeviceCatalog {
    return DeviceCatalogFromJSONTyped(json, false);
}

export function DeviceCatalogFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceCatalog {
    if (json == null) {
        return json;
    }
    return {
        
        'vendors': ((json['vendors'] as Array<any>).map(DeviceVendorFromJSON)),
        'version': json['version'],
    };
}

export function DeviceCatalogToJSON(json: any): DeviceCatalog {
    return DeviceCatalogToJSONTyped(json, false);
}

export function DeviceCatalogToJSONTyped(value?: DeviceCatalog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vendors': ((value['vendors'] as Array<any>).map(DeviceVendorToJSON)),
        'version': value['version'],
    };
}

