/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ForecastIngestItem } from './ForecastIngestItem';
import {
    ForecastIngestItemFromJSON,
    ForecastIngestItemFromJSONTyped,
    ForecastIngestItemToJSON,
    ForecastIngestItemToJSONTyped,
} from './ForecastIngestItem';

/**
 * 
 * @export
 * @interface ForecastIngestRequest
 */
export interface ForecastIngestRequest {
    /**
     * 
     * @type {Array<ForecastIngestItem>}
     * @memberof ForecastIngestRequest
     */
    items: Array<ForecastIngestItem>;
}

/**
 * Check if a given object implements the ForecastIngestRequest interface.
 */
export function instanceOfForecastIngestRequest(value: object): value is ForecastIngestRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ForecastIngestRequestFromJSON(json: any): ForecastIngestRequest {
    return ForecastIngestRequestFromJSONTyped(json, false);
}

export function ForecastIngestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForecastIngestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ForecastIngestItemFromJSON)),
    };
}

export function ForecastIngestRequestToJSON(json: any): ForecastIngestRequest {
    return ForecastIngestRequestToJSONTyped(json, false);
}

export function ForecastIngestRequestToJSONTyped(value?: ForecastIngestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ForecastIngestItemToJSON)),
    };
}

