/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HostKeyScanRequest
 */
export interface HostKeyScanRequest {
    /**
     * 
     * @type {string}
     * @memberof HostKeyScanRequest
     */
    host: string;
    /**
     * 
     * @type {number}
     * @memberof HostKeyScanRequest
     */
    port: number;
}

/**
 * Check if a given object implements the HostKeyScanRequest interface.
 */
export function instanceOfHostKeyScanRequest(value: object): value is HostKeyScanRequest {
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    return true;
}

export function HostKeyScanRequestFromJSON(json: any): HostKeyScanRequest {
    return HostKeyScanRequestFromJSONTyped(json, false);
}

export function HostKeyScanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HostKeyScanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'],
        'port': json['port'],
    };
}

export function HostKeyScanRequestToJSON(json: any): HostKeyScanRequest {
    return HostKeyScanRequestToJSONTyped(json, false);
}

export function HostKeyScanRequestToJSONTyped(value?: HostKeyScanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
        'port': value['port'],
    };
}

