/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncidentNoteResponse
 */
export interface IncidentNoteResponse {
    /**
     * 
     * @type {string}
     * @memberof IncidentNoteResponse
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof IncidentNoteResponse
     */
    created_at: string;
    /**
     * 
     * @type {string}
     * @memberof IncidentNoteResponse
     */
    created_by?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IncidentNoteResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof IncidentNoteResponse
     */
    incident_id: string;
}

/**
 * Check if a given object implements the IncidentNoteResponse interface.
 */
export function instanceOfIncidentNoteResponse(value: object): value is IncidentNoteResponse {
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incident_id' in value) || value['incident_id'] === undefined) return false;
    return true;
}

export function IncidentNoteResponseFromJSON(json: any): IncidentNoteResponse {
    return IncidentNoteResponseFromJSONTyped(json, false);
}

export function IncidentNoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentNoteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'created_at': json['created_at'],
        'created_by': json['created_by'] == null ? undefined : json['created_by'],
        'id': json['id'],
        'incident_id': json['incident_id'],
    };
}

export function IncidentNoteResponseToJSON(json: any): IncidentNoteResponse {
    return IncidentNoteResponseToJSONTyped(json, false);
}

export function IncidentNoteResponseToJSONTyped(value?: IncidentNoteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'created_at': value['created_at'],
        'created_by': value['created_by'],
        'id': value['id'],
        'incident_id': value['incident_id'],
    };
}

