/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlarmEventResponse } from './AlarmEventResponse';
import {
    AlarmEventResponseFromJSON,
    AlarmEventResponseFromJSONTyped,
    AlarmEventResponseToJSON,
    AlarmEventResponseToJSONTyped,
} from './AlarmEventResponse';
import type { IncidentResponse } from './IncidentResponse';
import {
    IncidentResponseFromJSON,
    IncidentResponseFromJSONTyped,
    IncidentResponseToJSON,
    IncidentResponseToJSONTyped,
} from './IncidentResponse';

/**
 * 
 * @export
 * @interface IncidentDetailResponse
 */
export interface IncidentDetailResponse {
    /**
     * 
     * @type {Array<AlarmEventResponse>}
     * @memberof IncidentDetailResponse
     */
    events: Array<AlarmEventResponse>;
    /**
     * 
     * @type {IncidentResponse}
     * @memberof IncidentDetailResponse
     */
    incident: IncidentResponse;
}

/**
 * Check if a given object implements the IncidentDetailResponse interface.
 */
export function instanceOfIncidentDetailResponse(value: object): value is IncidentDetailResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('incident' in value) || value['incident'] === undefined) return false;
    return true;
}

export function IncidentDetailResponseFromJSON(json: any): IncidentDetailResponse {
    return IncidentDetailResponseFromJSONTyped(json, false);
}

export function IncidentDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(AlarmEventResponseFromJSON)),
        'incident': IncidentResponseFromJSON(json['incident']),
    };
}

export function IncidentDetailResponseToJSON(json: any): IncidentDetailResponse {
    return IncidentDetailResponseToJSONTyped(json, false);
}

export function IncidentDetailResponseToJSONTyped(value?: IncidentDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': ((value['events'] as Array<any>).map(AlarmEventResponseToJSON)),
        'incident': IncidentResponseToJSON(value['incident']),
    };
}

