/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapLayerSnapshot
 */
export interface MapLayerSnapshot {
    /**
     * 
     * @type {any}
     * @memberof MapLayerSnapshot
     */
    config: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof MapLayerSnapshot
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof MapLayerSnapshot
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof MapLayerSnapshot
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof MapLayerSnapshot
     */
    opacity: number;
    /**
     * 
     * @type {string}
     * @memberof MapLayerSnapshot
     */
    source_type: string;
    /**
     * 
     * @type {string}
     * @memberof MapLayerSnapshot
     */
    system_key?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MapLayerSnapshot
     */
    z_index: number;
}

/**
 * Check if a given object implements the MapLayerSnapshot interface.
 */
export function instanceOfMapLayerSnapshot(value: object): value is MapLayerSnapshot {
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('opacity' in value) || value['opacity'] === undefined) return false;
    if (!('source_type' in value) || value['source_type'] === undefined) return false;
    if (!('z_index' in value) || value['z_index'] === undefined) return false;
    return true;
}

export function MapLayerSnapshotFromJSON(json: any): MapLayerSnapshot {
    return MapLayerSnapshotFromJSONTyped(json, false);
}

export function MapLayerSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapLayerSnapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'],
        'enabled': json['enabled'],
        'kind': json['kind'],
        'name': json['name'],
        'opacity': json['opacity'],
        'source_type': json['source_type'],
        'system_key': json['system_key'] == null ? undefined : json['system_key'],
        'z_index': json['z_index'],
    };
}

export function MapLayerSnapshotToJSON(json: any): MapLayerSnapshot {
    return MapLayerSnapshotToJSONTyped(json, false);
}

export function MapLayerSnapshotToJSONTyped(value?: MapLayerSnapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'enabled': value['enabled'],
        'kind': value['kind'],
        'name': value['name'],
        'opacity': value['opacity'],
        'source_type': value['source_type'],
        'system_key': value['system_key'],
        'z_index': value['z_index'],
    };
}

