/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapSettingsUpdateRequest
 */
export interface MapSettingsUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof MapSettingsUpdateRequest
     */
    active_base_layer_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MapSettingsUpdateRequest
     */
    bearing?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MapSettingsUpdateRequest
     */
    center_lat: number;
    /**
     * 
     * @type {number}
     * @memberof MapSettingsUpdateRequest
     */
    center_lng: number;
    /**
     * 
     * @type {number}
     * @memberof MapSettingsUpdateRequest
     */
    pitch?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MapSettingsUpdateRequest
     */
    zoom: number;
}

/**
 * Check if a given object implements the MapSettingsUpdateRequest interface.
 */
export function instanceOfMapSettingsUpdateRequest(value: object): value is MapSettingsUpdateRequest {
    if (!('center_lat' in value) || value['center_lat'] === undefined) return false;
    if (!('center_lng' in value) || value['center_lng'] === undefined) return false;
    if (!('zoom' in value) || value['zoom'] === undefined) return false;
    return true;
}

export function MapSettingsUpdateRequestFromJSON(json: any): MapSettingsUpdateRequest {
    return MapSettingsUpdateRequestFromJSONTyped(json, false);
}

export function MapSettingsUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapSettingsUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'active_base_layer_id': json['active_base_layer_id'] == null ? undefined : json['active_base_layer_id'],
        'bearing': json['bearing'] == null ? undefined : json['bearing'],
        'center_lat': json['center_lat'],
        'center_lng': json['center_lng'],
        'pitch': json['pitch'] == null ? undefined : json['pitch'],
        'zoom': json['zoom'],
    };
}

export function MapSettingsUpdateRequestToJSON(json: any): MapSettingsUpdateRequest {
    return MapSettingsUpdateRequestToJSONTyped(json, false);
}

export function MapSettingsUpdateRequestToJSONTyped(value?: MapSettingsUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_base_layer_id': value['active_base_layer_id'],
        'bearing': value['bearing'],
        'center_lat': value['center_lat'],
        'center_lng': value['center_lng'],
        'pitch': value['pitch'],
        'zoom': value['zoom'],
    };
}

