/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetricIngestItem } from './MetricIngestItem';
import {
    MetricIngestItemFromJSON,
    MetricIngestItemFromJSONTyped,
    MetricIngestItemToJSON,
    MetricIngestItemToJSONTyped,
} from './MetricIngestItem';

/**
 * 
 * @export
 * @interface MetricIngestRequest
 */
export interface MetricIngestRequest {
    /**
     * 
     * @type {Array<MetricIngestItem>}
     * @memberof MetricIngestRequest
     */
    items: Array<MetricIngestItem>;
}

/**
 * Check if a given object implements the MetricIngestRequest interface.
 */
export function instanceOfMetricIngestRequest(value: object): value is MetricIngestRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function MetricIngestRequestFromJSON(json: any): MetricIngestRequest {
    return MetricIngestRequestFromJSONTyped(json, false);
}

export function MetricIngestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricIngestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MetricIngestItemFromJSON)),
    };
}

export function MetricIngestRequestToJSON(json: any): MetricIngestRequest {
    return MetricIngestRequestToJSONTyped(json, false);
}

export function MetricIngestRequestToJSONTyped(value?: MetricIngestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MetricIngestItemToJSON)),
    };
}

