/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricIngestResponse
 */
export interface MetricIngestResponse {
    /**
     * 
     * @type {number}
     * @memberof MetricIngestResponse
     */
    ingested: number;
}

/**
 * Check if a given object implements the MetricIngestResponse interface.
 */
export function instanceOfMetricIngestResponse(value: object): value is MetricIngestResponse {
    if (!('ingested' in value) || value['ingested'] === undefined) return false;
    return true;
}

export function MetricIngestResponseFromJSON(json: any): MetricIngestResponse {
    return MetricIngestResponseFromJSONTyped(json, false);
}

export function MetricIngestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricIngestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ingested': json['ingested'],
    };
}

export function MetricIngestResponseToJSON(json: any): MetricIngestResponse {
    return MetricIngestResponseToJSONTyped(json, false);
}

export function MetricIngestResponseToJSONTyped(value?: MetricIngestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ingested': value['ingested'],
    };
}

