/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricIngestItem
 */
export interface MetricIngestItem {
    /**
     * 
     * @type {number}
     * @memberof MetricIngestItem
     */
    quality?: number;
    /**
     * 
     * @type {string}
     * @memberof MetricIngestItem
     */
    sensor_id: string;
    /**
     * 
     * @type {string}
     * @memberof MetricIngestItem
     */
    timestamp?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MetricIngestItem
     */
    value: number;
}

/**
 * Check if a given object implements the MetricIngestItem interface.
 */
export function instanceOfMetricIngestItem(value: object): value is MetricIngestItem {
    if (!('sensor_id' in value) || value['sensor_id'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function MetricIngestItemFromJSON(json: any): MetricIngestItem {
    return MetricIngestItemFromJSONTyped(json, false);
}

export function MetricIngestItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricIngestItem {
    if (json == null) {
        return json;
    }
    return {
        
        'quality': json['quality'] == null ? undefined : json['quality'],
        'sensor_id': json['sensor_id'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'value': json['value'],
    };
}

export function MetricIngestItemToJSON(json: any): MetricIngestItem {
    return MetricIngestItemToJSONTyped(json, false);
}

export function MetricIngestItemToJSONTyped(value?: MetricIngestItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quality': value['quality'],
        'sensor_id': value['sensor_id'],
        'timestamp': value['timestamp'],
        'value': value['value'],
    };
}

