/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeSensorDraft } from './NodeSensorDraft';
import {
    NodeSensorDraftFromJSON,
    NodeSensorDraftFromJSONTyped,
    NodeSensorDraftToJSON,
    NodeSensorDraftToJSONTyped,
} from './NodeSensorDraft';
import type { NodeAds1263SettingsDraft } from './NodeAds1263SettingsDraft';
import {
    NodeAds1263SettingsDraftFromJSON,
    NodeAds1263SettingsDraftFromJSONTyped,
    NodeAds1263SettingsDraftToJSON,
    NodeAds1263SettingsDraftToJSONTyped,
} from './NodeAds1263SettingsDraft';

/**
 * 
 * @export
 * @interface NodeSensorsConfigUpdateRequest
 */
export interface NodeSensorsConfigUpdateRequest {
    /**
     * 
     * @type {NodeAds1263SettingsDraft}
     * @memberof NodeSensorsConfigUpdateRequest
     */
    ads1263?: NodeAds1263SettingsDraft | null;
    /**
     * 
     * @type {Array<NodeSensorDraft>}
     * @memberof NodeSensorsConfigUpdateRequest
     */
    sensors: Array<NodeSensorDraft>;
}

/**
 * Check if a given object implements the NodeSensorsConfigUpdateRequest interface.
 */
export function instanceOfNodeSensorsConfigUpdateRequest(value: object): value is NodeSensorsConfigUpdateRequest {
    if (!('sensors' in value) || value['sensors'] === undefined) return false;
    return true;
}

export function NodeSensorsConfigUpdateRequestFromJSON(json: any): NodeSensorsConfigUpdateRequest {
    return NodeSensorsConfigUpdateRequestFromJSONTyped(json, false);
}

export function NodeSensorsConfigUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeSensorsConfigUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ads1263': json['ads1263'] == null ? undefined : NodeAds1263SettingsDraftFromJSON(json['ads1263']),
        'sensors': ((json['sensors'] as Array<any>).map(NodeSensorDraftFromJSON)),
    };
}

export function NodeSensorsConfigUpdateRequestToJSON(json: any): NodeSensorsConfigUpdateRequest {
    return NodeSensorsConfigUpdateRequestToJSONTyped(json, false);
}

export function NodeSensorsConfigUpdateRequestToJSONTyped(value?: NodeSensorsConfigUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ads1263': NodeAds1263SettingsDraftToJSON(value['ads1263']),
        'sensors': ((value['sensors'] as Array<any>).map(NodeSensorDraftToJSON)),
    };
}

