/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OfflineMapPackResponse
 */
export interface OfflineMapPackResponse {
    /**
     * 
     * @type {any}
     * @memberof OfflineMapPackResponse
     */
    bounds: any | null;
    /**
     * 
     * @type {string}
     * @memberof OfflineMapPackResponse
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OfflineMapPackResponse
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof OfflineMapPackResponse
     */
    max_zoom: number;
    /**
     * 
     * @type {number}
     * @memberof OfflineMapPackResponse
     */
    min_zoom: number;
    /**
     * 
     * @type {string}
     * @memberof OfflineMapPackResponse
     */
    name: string;
    /**
     * 
     * @type {any}
     * @memberof OfflineMapPackResponse
     */
    progress: any | null;
    /**
     * 
     * @type {string}
     * @memberof OfflineMapPackResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof OfflineMapPackResponse
     */
    updated_at: string;
}

/**
 * Check if a given object implements the OfflineMapPackResponse interface.
 */
export function instanceOfOfflineMapPackResponse(value: object): value is OfflineMapPackResponse {
    if (!('bounds' in value) || value['bounds'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('max_zoom' in value) || value['max_zoom'] === undefined) return false;
    if (!('min_zoom' in value) || value['min_zoom'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function OfflineMapPackResponseFromJSON(json: any): OfflineMapPackResponse {
    return OfflineMapPackResponseFromJSONTyped(json, false);
}

export function OfflineMapPackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfflineMapPackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bounds': json['bounds'],
        'error': json['error'] == null ? undefined : json['error'],
        'id': json['id'],
        'max_zoom': json['max_zoom'],
        'min_zoom': json['min_zoom'],
        'name': json['name'],
        'progress': json['progress'],
        'status': json['status'],
        'updated_at': json['updated_at'],
    };
}

export function OfflineMapPackResponseToJSON(json: any): OfflineMapPackResponse {
    return OfflineMapPackResponseToJSONTyped(json, false);
}

export function OfflineMapPackResponseToJSONTyped(value?: OfflineMapPackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bounds': value['bounds'],
        'error': value['error'],
        'id': value['id'],
        'max_zoom': value['max_zoom'],
        'min_zoom': value['min_zoom'],
        'name': value['name'],
        'progress': value['progress'],
        'status': value['status'],
        'updated_at': value['updated_at'],
    };
}

