/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputCreateRequest
 */
export interface OutputCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof OutputCreateRequest
     */
    command_topic?: string | null;
    /**
     * 
     * @type {any}
     * @memberof OutputCreateRequest
     */
    config?: any | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof OutputCreateRequest
     */
    history?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof OutputCreateRequest
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutputCreateRequest
     */
    last_command?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutputCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OutputCreateRequest
     */
    node_id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OutputCreateRequest
     */
    schedule_ids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OutputCreateRequest
     */
    state?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof OutputCreateRequest
     */
    supported_states?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OutputCreateRequest
     */
    type: string;
}

/**
 * Check if a given object implements the OutputCreateRequest interface.
 */
export function instanceOfOutputCreateRequest(value: object): value is OutputCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('node_id' in value) || value['node_id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function OutputCreateRequestFromJSON(json: any): OutputCreateRequest {
    return OutputCreateRequestFromJSONTyped(json, false);
}

export function OutputCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'command_topic': json['command_topic'] == null ? undefined : json['command_topic'],
        'config': json['config'] == null ? undefined : json['config'],
        'history': json['history'] == null ? undefined : json['history'],
        'id': json['id'] == null ? undefined : json['id'],
        'last_command': json['last_command'] == null ? undefined : json['last_command'],
        'name': json['name'],
        'node_id': json['node_id'],
        'schedule_ids': json['schedule_ids'] == null ? undefined : json['schedule_ids'],
        'state': json['state'] == null ? undefined : json['state'],
        'supported_states': json['supported_states'] == null ? undefined : json['supported_states'],
        'type': json['type'],
    };
}

export function OutputCreateRequestToJSON(json: any): OutputCreateRequest {
    return OutputCreateRequestToJSONTyped(json, false);
}

export function OutputCreateRequestToJSONTyped(value?: OutputCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command_topic': value['command_topic'],
        'config': value['config'],
        'history': value['history'],
        'id': value['id'],
        'last_command': value['last_command'],
        'name': value['name'],
        'node_id': value['node_id'],
        'schedule_ids': value['schedule_ids'],
        'state': value['state'],
        'supported_states': value['supported_states'],
        'type': value['type'],
    };
}

