/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PiDeploymentRequest
 */
export interface PiDeploymentRequest {
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    adoption_token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    host: string;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    host_key_fingerprint?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    mqtt_password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    mqtt_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    mqtt_username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    node_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    node_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    password: string;
    /**
     * 
     * @type {number}
     * @memberof PiDeploymentRequest
     */
    port: number;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    ssh_private_key_passphrase?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    ssh_private_key_pem?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PiDeploymentRequest
     */
    username: string;
}

/**
 * Check if a given object implements the PiDeploymentRequest interface.
 */
export function instanceOfPiDeploymentRequest(value: object): value is PiDeploymentRequest {
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function PiDeploymentRequestFromJSON(json: any): PiDeploymentRequest {
    return PiDeploymentRequestFromJSONTyped(json, false);
}

export function PiDeploymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PiDeploymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'adoption_token': json['adoption_token'] == null ? undefined : json['adoption_token'],
        'host': json['host'],
        'host_key_fingerprint': json['host_key_fingerprint'] == null ? undefined : json['host_key_fingerprint'],
        'mqtt_password': json['mqtt_password'] == null ? undefined : json['mqtt_password'],
        'mqtt_url': json['mqtt_url'] == null ? undefined : json['mqtt_url'],
        'mqtt_username': json['mqtt_username'] == null ? undefined : json['mqtt_username'],
        'node_id': json['node_id'] == null ? undefined : json['node_id'],
        'node_name': json['node_name'] == null ? undefined : json['node_name'],
        'password': json['password'],
        'port': json['port'],
        'ssh_private_key_passphrase': json['ssh_private_key_passphrase'] == null ? undefined : json['ssh_private_key_passphrase'],
        'ssh_private_key_pem': json['ssh_private_key_pem'] == null ? undefined : json['ssh_private_key_pem'],
        'username': json['username'],
    };
}

export function PiDeploymentRequestToJSON(json: any): PiDeploymentRequest {
    return PiDeploymentRequestToJSONTyped(json, false);
}

export function PiDeploymentRequestToJSONTyped(value?: PiDeploymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adoption_token': value['adoption_token'],
        'host': value['host'],
        'host_key_fingerprint': value['host_key_fingerprint'],
        'mqtt_password': value['mqtt_password'],
        'mqtt_url': value['mqtt_url'],
        'mqtt_username': value['mqtt_username'],
        'node_id': value['node_id'],
        'node_name': value['node_name'],
        'password': value['password'],
        'port': value['port'],
        'ssh_private_key_passphrase': value['ssh_private_key_passphrase'],
        'ssh_private_key_pem': value['ssh_private_key_pem'],
        'username': value['username'],
    };
}

