/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PowerRunwayConfig
 */
export interface PowerRunwayConfig {
    /**
     * 
     * @type {boolean}
     * @memberof PowerRunwayConfig
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PowerRunwayConfig
     */
    history_days?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PowerRunwayConfig
     */
    load_sensor_ids?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof PowerRunwayConfig
     */
    projection_days?: number;
    /**
     * 
     * @type {number}
     * @memberof PowerRunwayConfig
     */
    pv_derate?: number;
}

/**
 * Check if a given object implements the PowerRunwayConfig interface.
 */
export function instanceOfPowerRunwayConfig(value: object): value is PowerRunwayConfig {
    return true;
}

export function PowerRunwayConfigFromJSON(json: any): PowerRunwayConfig {
    return PowerRunwayConfigFromJSONTyped(json, false);
}

export function PowerRunwayConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerRunwayConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'history_days': json['history_days'] == null ? undefined : json['history_days'],
        'load_sensor_ids': json['load_sensor_ids'] == null ? undefined : json['load_sensor_ids'],
        'projection_days': json['projection_days'] == null ? undefined : json['projection_days'],
        'pv_derate': json['pv_derate'] == null ? undefined : json['pv_derate'],
    };
}

export function PowerRunwayConfigToJSON(json: any): PowerRunwayConfig {
    return PowerRunwayConfigToJSONTyped(json, false);
}

export function PowerRunwayConfigToJSONTyped(value?: PowerRunwayConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'history_days': value['history_days'],
        'load_sensor_ids': value['load_sensor_ids'],
        'projection_days': value['projection_days'],
        'pv_derate': value['pv_derate'],
    };
}

