/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreviewEventOverlaysV1
 */
export interface PreviewEventOverlaysV1 {
    /**
     * 
     * @type {Array<number>}
     * @memberof PreviewEventOverlaysV1
     */
    candidate_event_ts_ms: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PreviewEventOverlaysV1
     */
    focus_event_ts_ms: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PreviewEventOverlaysV1
     */
    matched_candidate_event_ts_ms: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PreviewEventOverlaysV1
     */
    matched_focus_event_ts_ms: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof PreviewEventOverlaysV1
     */
    tolerance_seconds?: number | null;
}

/**
 * Check if a given object implements the PreviewEventOverlaysV1 interface.
 */
export function instanceOfPreviewEventOverlaysV1(value: object): value is PreviewEventOverlaysV1 {
    if (!('candidate_event_ts_ms' in value) || value['candidate_event_ts_ms'] === undefined) return false;
    if (!('focus_event_ts_ms' in value) || value['focus_event_ts_ms'] === undefined) return false;
    if (!('matched_candidate_event_ts_ms' in value) || value['matched_candidate_event_ts_ms'] === undefined) return false;
    if (!('matched_focus_event_ts_ms' in value) || value['matched_focus_event_ts_ms'] === undefined) return false;
    return true;
}

export function PreviewEventOverlaysV1FromJSON(json: any): PreviewEventOverlaysV1 {
    return PreviewEventOverlaysV1FromJSONTyped(json, false);
}

export function PreviewEventOverlaysV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewEventOverlaysV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'candidate_event_ts_ms': json['candidate_event_ts_ms'],
        'focus_event_ts_ms': json['focus_event_ts_ms'],
        'matched_candidate_event_ts_ms': json['matched_candidate_event_ts_ms'],
        'matched_focus_event_ts_ms': json['matched_focus_event_ts_ms'],
        'tolerance_seconds': json['tolerance_seconds'] == null ? undefined : json['tolerance_seconds'],
    };
}

export function PreviewEventOverlaysV1ToJSON(json: any): PreviewEventOverlaysV1 {
    return PreviewEventOverlaysV1ToJSONTyped(json, false);
}

export function PreviewEventOverlaysV1ToJSONTyped(value?: PreviewEventOverlaysV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'candidate_event_ts_ms': value['candidate_event_ts_ms'],
        'focus_event_ts_ms': value['focus_event_ts_ms'],
        'matched_candidate_event_ts_ms': value['matched_candidate_event_ts_ms'],
        'matched_focus_event_ts_ms': value['matched_focus_event_ts_ms'],
        'tolerance_seconds': value['tolerance_seconds'],
    };
}

