/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventPolarityV1 } from './EventPolarityV1';
import {
    EventPolarityV1FromJSON,
    EventPolarityV1FromJSONTyped,
    EventPolarityV1ToJSON,
    EventPolarityV1ToJSONTyped,
} from './EventPolarityV1';

/**
 * 
 * @export
 * @interface PreviewEventOverlayParamsV1
 */
export interface PreviewEventOverlayParamsV1 {
    /**
     * 
     * @type {number}
     * @memberof PreviewEventOverlayParamsV1
     */
    gap_max_buckets?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PreviewEventOverlayParamsV1
     */
    max_events?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PreviewEventOverlayParamsV1
     */
    min_separation_buckets?: number | null;
    /**
     * 
     * @type {EventPolarityV1}
     * @memberof PreviewEventOverlayParamsV1
     */
    polarity?: EventPolarityV1 | null;
    /**
     * 
     * @type {number}
     * @memberof PreviewEventOverlayParamsV1
     */
    tolerance_seconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PreviewEventOverlayParamsV1
     */
    z_threshold?: number | null;
}



/**
 * Check if a given object implements the PreviewEventOverlayParamsV1 interface.
 */
export function instanceOfPreviewEventOverlayParamsV1(value: object): value is PreviewEventOverlayParamsV1 {
    return true;
}

export function PreviewEventOverlayParamsV1FromJSON(json: any): PreviewEventOverlayParamsV1 {
    return PreviewEventOverlayParamsV1FromJSONTyped(json, false);
}

export function PreviewEventOverlayParamsV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewEventOverlayParamsV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'gap_max_buckets': json['gap_max_buckets'] == null ? undefined : json['gap_max_buckets'],
        'max_events': json['max_events'] == null ? undefined : json['max_events'],
        'min_separation_buckets': json['min_separation_buckets'] == null ? undefined : json['min_separation_buckets'],
        'polarity': json['polarity'] == null ? undefined : EventPolarityV1FromJSON(json['polarity']),
        'tolerance_seconds': json['tolerance_seconds'] == null ? undefined : json['tolerance_seconds'],
        'z_threshold': json['z_threshold'] == null ? undefined : json['z_threshold'],
    };
}

export function PreviewEventOverlayParamsV1ToJSON(json: any): PreviewEventOverlayParamsV1 {
    return PreviewEventOverlayParamsV1ToJSONTyped(json, false);
}

export function PreviewEventOverlayParamsV1ToJSONTyped(value?: PreviewEventOverlayParamsV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gap_max_buckets': value['gap_max_buckets'],
        'max_events': value['max_events'],
        'min_separation_buckets': value['min_separation_buckets'],
        'polarity': EventPolarityV1ToJSON(value['polarity']),
        'tolerance_seconds': value['tolerance_seconds'],
        'z_threshold': value['z_threshold'],
    };
}

