/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PvForecastCheckRequest
 */
export interface PvForecastCheckRequest {
    /**
     * 
     * @type {number}
     * @memberof PvForecastCheckRequest
     */
    azimuth_deg: number;
    /**
     * 
     * @type {number}
     * @memberof PvForecastCheckRequest
     */
    kwp: number;
    /**
     * 
     * @type {number}
     * @memberof PvForecastCheckRequest
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof PvForecastCheckRequest
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof PvForecastCheckRequest
     */
    tilt_deg: number;
}

/**
 * Check if a given object implements the PvForecastCheckRequest interface.
 */
export function instanceOfPvForecastCheckRequest(value: object): value is PvForecastCheckRequest {
    if (!('azimuth_deg' in value) || value['azimuth_deg'] === undefined) return false;
    if (!('kwp' in value) || value['kwp'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('tilt_deg' in value) || value['tilt_deg'] === undefined) return false;
    return true;
}

export function PvForecastCheckRequestFromJSON(json: any): PvForecastCheckRequest {
    return PvForecastCheckRequestFromJSONTyped(json, false);
}

export function PvForecastCheckRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PvForecastCheckRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'azimuth_deg': json['azimuth_deg'],
        'kwp': json['kwp'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'tilt_deg': json['tilt_deg'],
    };
}

export function PvForecastCheckRequestToJSON(json: any): PvForecastCheckRequest {
    return PvForecastCheckRequestToJSONTyped(json, false);
}

export function PvForecastCheckRequestToJSONTyped(value?: PvForecastCheckRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'azimuth_deg': value['azimuth_deg'],
        'kwp': value['kwp'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'tilt_deg': value['tilt_deg'],
    };
}

