/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterCloudSiteRequest
 */
export interface RegisterCloudSiteRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterCloudSiteRequest
     */
    site_key: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCloudSiteRequest
     */
    site_name: string;
}

/**
 * Check if a given object implements the RegisterCloudSiteRequest interface.
 */
export function instanceOfRegisterCloudSiteRequest(value: object): value is RegisterCloudSiteRequest {
    if (!('site_key' in value) || value['site_key'] === undefined) return false;
    if (!('site_name' in value) || value['site_name'] === undefined) return false;
    return true;
}

export function RegisterCloudSiteRequestFromJSON(json: any): RegisterCloudSiteRequest {
    return RegisterCloudSiteRequestFromJSONTyped(json, false);
}

export function RegisterCloudSiteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterCloudSiteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'site_key': json['site_key'],
        'site_name': json['site_name'],
    };
}

export function RegisterCloudSiteRequestToJSON(json: any): RegisterCloudSiteRequest {
    return RegisterCloudSiteRequestToJSONTyped(json, false);
}

export function RegisterCloudSiteRequestToJSONTyped(value?: RegisterCloudSiteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'site_key': value['site_key'],
        'site_name': value['site_name'],
    };
}

