/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenogyValidateResponse
 */
export interface RenogyValidateResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof RenogyValidateResponse
     */
    errors: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof RenogyValidateResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the RenogyValidateResponse interface.
 */
export function instanceOfRenogyValidateResponse(value: object): value is RenogyValidateResponse {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function RenogyValidateResponseFromJSON(json: any): RenogyValidateResponse {
    return RenogyValidateResponseFromJSONTyped(json, false);
}

export function RenogyValidateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenogyValidateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'],
        'ok': json['ok'],
    };
}

export function RenogyValidateResponseToJSON(json: any): RenogyValidateResponse {
    return RenogyValidateResponseToJSONTyped(json, false);
}

export function RenogyValidateResponseToJSONTyped(value?: RenogyValidateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'],
        'ok': value['ok'],
    };
}

