/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenogyHistoryEntry
 */
export interface RenogyHistoryEntry {
    /**
     * 
     * @type {string}
     * @memberof RenogyHistoryEntry
     */
    created_at: string;
    /**
     * 
     * @type {any}
     * @memberof RenogyHistoryEntry
     */
    current?: any | null;
    /**
     * 
     * @type {any}
     * @memberof RenogyHistoryEntry
     */
    desired?: any | null;
    /**
     * 
     * @type {any}
     * @memberof RenogyHistoryEntry
     */
    diff?: any | null;
    /**
     * 
     * @type {string}
     * @memberof RenogyHistoryEntry
     */
    event_type: string;
    /**
     * 
     * @type {number}
     * @memberof RenogyHistoryEntry
     */
    id: number;
    /**
     * 
     * @type {any}
     * @memberof RenogyHistoryEntry
     */
    result?: any | null;
}

/**
 * Check if a given object implements the RenogyHistoryEntry interface.
 */
export function instanceOfRenogyHistoryEntry(value: object): value is RenogyHistoryEntry {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('event_type' in value) || value['event_type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function RenogyHistoryEntryFromJSON(json: any): RenogyHistoryEntry {
    return RenogyHistoryEntryFromJSONTyped(json, false);
}

export function RenogyHistoryEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenogyHistoryEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': json['created_at'],
        'current': json['current'] == null ? undefined : json['current'],
        'desired': json['desired'] == null ? undefined : json['desired'],
        'diff': json['diff'] == null ? undefined : json['diff'],
        'event_type': json['event_type'],
        'id': json['id'],
        'result': json['result'] == null ? undefined : json['result'],
    };
}

export function RenogyHistoryEntryToJSON(json: any): RenogyHistoryEntry {
    return RenogyHistoryEntryToJSONTyped(json, false);
}

export function RenogyHistoryEntryToJSONTyped(value?: RenogyHistoryEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'],
        'current': value['current'],
        'desired': value['desired'],
        'diff': value['diff'],
        'event_type': value['event_type'],
        'id': value['id'],
        'result': value['result'],
    };
}

