/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestoreResponse
 */
export interface RestoreResponse {
    /**
     * 
     * @type {string}
     * @memberof RestoreResponse
     */
    status: string;
}

/**
 * Check if a given object implements the RestoreResponse interface.
 */
export function instanceOfRestoreResponse(value: object): value is RestoreResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RestoreResponseFromJSON(json: any): RestoreResponse {
    return RestoreResponseFromJSONTyped(json, false);
}

export function RestoreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestoreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function RestoreResponseToJSON(json: any): RestoreResponse {
    return RestoreResponseToJSONTyped(json, false);
}

export function RestoreResponseToJSONTyped(value?: RestoreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

