/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleResponse
 */
export interface ScheduleResponse {
    /**
     * 
     * @type {Array<any>}
     * @memberof ScheduleResponse
     */
    actions: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ScheduleResponse
     */
    blocks: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ScheduleResponse
     */
    conditions: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof ScheduleResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduleResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduleResponse
     */
    next_run?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduleResponse
     */
    rrule: string;
}

/**
 * Check if a given object implements the ScheduleResponse interface.
 */
export function instanceOfScheduleResponse(value: object): value is ScheduleResponse {
    if (!('actions' in value) || value['actions'] === undefined) return false;
    if (!('blocks' in value) || value['blocks'] === undefined) return false;
    if (!('conditions' in value) || value['conditions'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('rrule' in value) || value['rrule'] === undefined) return false;
    return true;
}

export function ScheduleResponseFromJSON(json: any): ScheduleResponse {
    return ScheduleResponseFromJSONTyped(json, false);
}

export function ScheduleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'actions': json['actions'],
        'blocks': json['blocks'],
        'conditions': json['conditions'],
        'id': json['id'],
        'name': json['name'],
        'next_run': json['next_run'] == null ? undefined : json['next_run'],
        'rrule': json['rrule'],
    };
}

export function ScheduleResponseToJSON(json: any): ScheduleResponse {
    return ScheduleResponseToJSONTyped(json, false);
}

export function ScheduleResponseToJSONTyped(value?: ScheduleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actions': value['actions'],
        'blocks': value['blocks'],
        'conditions': value['conditions'],
        'id': value['id'],
        'name': value['name'],
        'next_run': value['next_run'],
        'rrule': value['rrule'],
    };
}

