/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupConfigSnapshot
 */
export interface SetupConfigSnapshot {
    /**
     * 
     * @type {string}
     * @memberof SetupConfigSnapshot
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof SetupConfigSnapshot
     */
    updated_at?: string | null;
    /**
     * 
     * @type {any}
     * @memberof SetupConfigSnapshot
     */
    value: any | null;
}

/**
 * Check if a given object implements the SetupConfigSnapshot interface.
 */
export function instanceOfSetupConfigSnapshot(value: object): value is SetupConfigSnapshot {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function SetupConfigSnapshotFromJSON(json: any): SetupConfigSnapshot {
    return SetupConfigSnapshotFromJSONTyped(json, false);
}

export function SetupConfigSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupConfigSnapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
        'value': json['value'],
    };
}

export function SetupConfigSnapshotToJSON(json: any): SetupConfigSnapshot {
    return SetupConfigSnapshotToJSONTyped(json, false);
}

export function SetupConfigSnapshotToJSONTyped(value?: SetupConfigSnapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'updated_at': value['updated_at'],
        'value': value['value'],
    };
}

