/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupCredential
 */
export interface SetupCredential {
    /**
     * 
     * @type {string}
     * @memberof SetupCredential
     */
    created_at?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SetupCredential
     */
    has_value: boolean;
    /**
     * 
     * @type {any}
     * @memberof SetupCredential
     */
    metadata: any | null;
    /**
     * 
     * @type {string}
     * @memberof SetupCredential
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SetupCredential
     */
    updated_at?: string | null;
}

/**
 * Check if a given object implements the SetupCredential interface.
 */
export function instanceOfSetupCredential(value: object): value is SetupCredential {
    if (!('has_value' in value) || value['has_value'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SetupCredentialFromJSON(json: any): SetupCredential {
    return SetupCredentialFromJSONTyped(json, false);
}

export function SetupCredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupCredential {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'has_value': json['has_value'],
        'metadata': json['metadata'],
        'name': json['name'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function SetupCredentialToJSON(json: any): SetupCredential {
    return SetupCredentialToJSONTyped(json, false);
}

export function SetupCredentialToJSONTyped(value?: SetupCredential | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'],
        'has_value': value['has_value'],
        'metadata': value['metadata'],
        'name': value['name'],
        'updated_at': value['updated_at'],
    };
}

