/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupCredentialSnapshot
 */
export interface SetupCredentialSnapshot {
    /**
     * 
     * @type {any}
     * @memberof SetupCredentialSnapshot
     */
    metadata: any | null;
    /**
     * 
     * @type {string}
     * @memberof SetupCredentialSnapshot
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SetupCredentialSnapshot
     */
    value: string;
}

/**
 * Check if a given object implements the SetupCredentialSnapshot interface.
 */
export function instanceOfSetupCredentialSnapshot(value: object): value is SetupCredentialSnapshot {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function SetupCredentialSnapshotFromJSON(json: any): SetupCredentialSnapshot {
    return SetupCredentialSnapshotFromJSONTyped(json, false);
}

export function SetupCredentialSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupCredentialSnapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'],
        'name': json['name'],
        'value': json['value'],
    };
}

export function SetupCredentialSnapshotToJSON(json: any): SetupCredentialSnapshot {
    return SetupCredentialSnapshotToJSONTyped(json, false);
}

export function SetupCredentialSnapshotToJSONTyped(value?: SetupCredentialSnapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': value['metadata'],
        'name': value['name'],
        'value': value['value'],
    };
}

