/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StepStatus = {
    pending: 'pending',
    running: 'running',
    completed: 'completed',
    failed: 'failed'
} as const;
export type StepStatus = typeof StepStatus[keyof typeof StepStatus];


export function instanceOfStepStatus(value: any): boolean {
    for (const key in StepStatus) {
        if (Object.prototype.hasOwnProperty.call(StepStatus, key)) {
            if (StepStatus[key as keyof typeof StepStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StepStatusFromJSON(json: any): StepStatus {
    return StepStatusFromJSONTyped(json, false);
}

export function StepStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepStatus {
    return json as StepStatus;
}

export function StepStatusToJSON(value?: StepStatus | null): any {
    return value as any;
}

export function StepStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): StepStatus {
    return value as StepStatus;
}

