/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TsseEpisodeV1
 */
export interface TsseEpisodeV1 {
    /**
     * 
     * @type {number}
     * @memberof TsseEpisodeV1
     */
    coverage: number;
    /**
     * 
     * @type {string}
     * @memberof TsseEpisodeV1
     */
    end_ts: string;
    /**
     * 
     * @type {number}
     * @memberof TsseEpisodeV1
     */
    lag_iqr_sec: number;
    /**
     * 
     * @type {number}
     * @memberof TsseEpisodeV1
     */
    lag_sec: number;
    /**
     * 
     * @type {number}
     * @memberof TsseEpisodeV1
     */
    num_points: number;
    /**
     * 
     * @type {number}
     * @memberof TsseEpisodeV1
     */
    score_mean: number;
    /**
     * 
     * @type {number}
     * @memberof TsseEpisodeV1
     */
    score_peak: number;
    /**
     * 
     * @type {string}
     * @memberof TsseEpisodeV1
     */
    start_ts: string;
    /**
     * 
     * @type {number}
     * @memberof TsseEpisodeV1
     */
    window_sec: number;
}

/**
 * Check if a given object implements the TsseEpisodeV1 interface.
 */
export function instanceOfTsseEpisodeV1(value: object): value is TsseEpisodeV1 {
    if (!('coverage' in value) || value['coverage'] === undefined) return false;
    if (!('end_ts' in value) || value['end_ts'] === undefined) return false;
    if (!('lag_iqr_sec' in value) || value['lag_iqr_sec'] === undefined) return false;
    if (!('lag_sec' in value) || value['lag_sec'] === undefined) return false;
    if (!('num_points' in value) || value['num_points'] === undefined) return false;
    if (!('score_mean' in value) || value['score_mean'] === undefined) return false;
    if (!('score_peak' in value) || value['score_peak'] === undefined) return false;
    if (!('start_ts' in value) || value['start_ts'] === undefined) return false;
    if (!('window_sec' in value) || value['window_sec'] === undefined) return false;
    return true;
}

export function TsseEpisodeV1FromJSON(json: any): TsseEpisodeV1 {
    return TsseEpisodeV1FromJSONTyped(json, false);
}

export function TsseEpisodeV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): TsseEpisodeV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'coverage': json['coverage'],
        'end_ts': json['end_ts'],
        'lag_iqr_sec': json['lag_iqr_sec'],
        'lag_sec': json['lag_sec'],
        'num_points': json['num_points'],
        'score_mean': json['score_mean'],
        'score_peak': json['score_peak'],
        'start_ts': json['start_ts'],
        'window_sec': json['window_sec'],
    };
}

export function TsseEpisodeV1ToJSON(json: any): TsseEpisodeV1 {
    return TsseEpisodeV1ToJSONTyped(json, false);
}

export function TsseEpisodeV1ToJSONTyped(value?: TsseEpisodeV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coverage': value['coverage'],
        'end_ts': value['end_ts'],
        'lag_iqr_sec': value['lag_iqr_sec'],
        'lag_sec': value['lag_sec'],
        'num_points': value['num_points'],
        'score_mean': value['score_mean'],
        'score_peak': value['score_peak'],
        'start_ts': value['start_ts'],
        'window_sec': value['window_sec'],
    };
}

