/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PreviewEventOverlaysV1 } from './PreviewEventOverlaysV1';
import {
    PreviewEventOverlaysV1FromJSON,
    PreviewEventOverlaysV1FromJSONTyped,
    PreviewEventOverlaysV1ToJSON,
    PreviewEventOverlaysV1ToJSONTyped,
} from './PreviewEventOverlaysV1';
import type { TsseEpisodeV1 } from './TsseEpisodeV1';
import {
    TsseEpisodeV1FromJSON,
    TsseEpisodeV1FromJSONTyped,
    TsseEpisodeV1ToJSON,
    TsseEpisodeV1ToJSONTyped,
} from './TsseEpisodeV1';
import type { TssePreviewSeriesV1 } from './TssePreviewSeriesV1';
import {
    TssePreviewSeriesV1FromJSON,
    TssePreviewSeriesV1FromJSONTyped,
    TssePreviewSeriesV1ToJSON,
    TssePreviewSeriesV1ToJSONTyped,
} from './TssePreviewSeriesV1';

/**
 * 
 * @export
 * @interface TssePreviewResponseV1
 */
export interface TssePreviewResponseV1 {
    /**
     * 
     * @type {number}
     * @memberof TssePreviewResponseV1
     */
    bucket_seconds: number;
    /**
     * 
     * @type {TssePreviewSeriesV1}
     * @memberof TssePreviewResponseV1
     */
    candidate: TssePreviewSeriesV1;
    /**
     * 
     * @type {TssePreviewSeriesV1}
     * @memberof TssePreviewResponseV1
     */
    candidate_aligned?: TssePreviewSeriesV1 | null;
    /**
     * 
     * @type {PreviewEventOverlaysV1}
     * @memberof TssePreviewResponseV1
     */
    event_overlays?: PreviewEventOverlaysV1 | null;
    /**
     * 
     * @type {TssePreviewSeriesV1}
     * @memberof TssePreviewResponseV1
     */
    focus: TssePreviewSeriesV1;
    /**
     * 
     * @type {TsseEpisodeV1}
     * @memberof TssePreviewResponseV1
     */
    selected_episode?: TsseEpisodeV1 | null;
}

/**
 * Check if a given object implements the TssePreviewResponseV1 interface.
 */
export function instanceOfTssePreviewResponseV1(value: object): value is TssePreviewResponseV1 {
    if (!('bucket_seconds' in value) || value['bucket_seconds'] === undefined) return false;
    if (!('candidate' in value) || value['candidate'] === undefined) return false;
    if (!('focus' in value) || value['focus'] === undefined) return false;
    return true;
}

export function TssePreviewResponseV1FromJSON(json: any): TssePreviewResponseV1 {
    return TssePreviewResponseV1FromJSONTyped(json, false);
}

export function TssePreviewResponseV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): TssePreviewResponseV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'bucket_seconds': json['bucket_seconds'],
        'candidate': TssePreviewSeriesV1FromJSON(json['candidate']),
        'candidate_aligned': json['candidate_aligned'] == null ? undefined : TssePreviewSeriesV1FromJSON(json['candidate_aligned']),
        'event_overlays': json['event_overlays'] == null ? undefined : PreviewEventOverlaysV1FromJSON(json['event_overlays']),
        'focus': TssePreviewSeriesV1FromJSON(json['focus']),
        'selected_episode': json['selected_episode'] == null ? undefined : TsseEpisodeV1FromJSON(json['selected_episode']),
    };
}

export function TssePreviewResponseV1ToJSON(json: any): TssePreviewResponseV1 {
    return TssePreviewResponseV1ToJSONTyped(json, false);
}

export function TssePreviewResponseV1ToJSONTyped(value?: TssePreviewResponseV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bucket_seconds': value['bucket_seconds'],
        'candidate': TssePreviewSeriesV1ToJSON(value['candidate']),
        'candidate_aligned': TssePreviewSeriesV1ToJSON(value['candidate_aligned']),
        'event_overlays': PreviewEventOverlaysV1ToJSON(value['event_overlays']),
        'focus': TssePreviewSeriesV1ToJSON(value['focus']),
        'selected_episode': TsseEpisodeV1ToJSON(value['selected_episode']),
    };
}

