/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAnnotationRequest
 */
export interface UpdateAnnotationRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateAnnotationRequest
     */
    chart_state?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAnnotationRequest
     */
    label?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAnnotationRequest
     */
    sensor_ids?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAnnotationRequest
     */
    time_end?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAnnotationRequest
     */
    time_start?: string | null;
}

/**
 * Check if a given object implements the UpdateAnnotationRequest interface.
 */
export function instanceOfUpdateAnnotationRequest(value: object): value is UpdateAnnotationRequest {
    return true;
}

export function UpdateAnnotationRequestFromJSON(json: any): UpdateAnnotationRequest {
    return UpdateAnnotationRequestFromJSONTyped(json, false);
}

export function UpdateAnnotationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAnnotationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chart_state': json['chart_state'] == null ? undefined : json['chart_state'],
        'label': json['label'] == null ? undefined : json['label'],
        'sensor_ids': json['sensor_ids'] == null ? undefined : json['sensor_ids'],
        'time_end': json['time_end'] == null ? undefined : json['time_end'],
        'time_start': json['time_start'] == null ? undefined : json['time_start'],
    };
}

export function UpdateAnnotationRequestToJSON(json: any): UpdateAnnotationRequest {
    return UpdateAnnotationRequestToJSONTyped(json, false);
}

export function UpdateAnnotationRequestToJSONTyped(value?: UpdateAnnotationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chart_state': value['chart_state'],
        'label': value['label'],
        'sensor_ids': value['sensor_ids'],
        'time_end': value['time_end'],
        'time_start': value['time_start'],
    };
}

