/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertCredentialRequest
 */
export interface UpsertCredentialRequest {
    /**
     * 
     * @type {any}
     * @memberof UpsertCredentialRequest
     */
    metadata?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertCredentialRequest
     */
    value: string;
}

/**
 * Check if a given object implements the UpsertCredentialRequest interface.
 */
export function instanceOfUpsertCredentialRequest(value: object): value is UpsertCredentialRequest {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function UpsertCredentialRequestFromJSON(json: any): UpsertCredentialRequest {
    return UpsertCredentialRequestFromJSONTyped(json, false);
}

export function UpsertCredentialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertCredentialRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'value': json['value'],
    };
}

export function UpsertCredentialRequestToJSON(json: any): UpsertCredentialRequest {
    return UpsertCredentialRequestToJSONTyped(json, false);
}

export function UpsertCredentialRequestToJSONTyped(value?: UpsertCredentialRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': value['metadata'],
        'value': value['value'],
    };
}

