/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ws2902CreatedSensor
 */
export interface Ws2902CreatedSensor {
    /**
     * 
     * @type {number}
     * @memberof Ws2902CreatedSensor
     */
    interval_seconds: number;
    /**
     * 
     * @type {string}
     * @memberof Ws2902CreatedSensor
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Ws2902CreatedSensor
     */
    sensor_id: string;
    /**
     * 
     * @type {string}
     * @memberof Ws2902CreatedSensor
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof Ws2902CreatedSensor
     */
    unit: string;
}

/**
 * Check if a given object implements the Ws2902CreatedSensor interface.
 */
export function instanceOfWs2902CreatedSensor(value: object): value is Ws2902CreatedSensor {
    if (!('interval_seconds' in value) || value['interval_seconds'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sensor_id' in value) || value['sensor_id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function Ws2902CreatedSensorFromJSON(json: any): Ws2902CreatedSensor {
    return Ws2902CreatedSensorFromJSONTyped(json, false);
}

export function Ws2902CreatedSensorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ws2902CreatedSensor {
    if (json == null) {
        return json;
    }
    return {
        
        'interval_seconds': json['interval_seconds'],
        'name': json['name'],
        'sensor_id': json['sensor_id'],
        'type': json['type'],
        'unit': json['unit'],
    };
}

export function Ws2902CreatedSensorToJSON(json: any): Ws2902CreatedSensor {
    return Ws2902CreatedSensorToJSONTyped(json, false);
}

export function Ws2902CreatedSensorToJSONTyped(value?: Ws2902CreatedSensor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interval_seconds': value['interval_seconds'],
        'name': value['name'],
        'sensor_id': value['sensor_id'],
        'type': value['type'],
        'unit': value['unit'],
    };
}

