/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlarmRuleDeleteResponse,
  AlarmRulePreviewRequest,
  AlarmRulePreviewResponse,
  AlarmRuleResponse,
  AlarmRuleStatsRequest,
  AlarmRuleStatsResponse,
  CreateAlarmRuleRequest,
  UpdateAlarmRuleRequest,
} from '../models/index';
import {
    AlarmRuleDeleteResponseFromJSON,
    AlarmRuleDeleteResponseToJSON,
    AlarmRulePreviewRequestFromJSON,
    AlarmRulePreviewRequestToJSON,
    AlarmRulePreviewResponseFromJSON,
    AlarmRulePreviewResponseToJSON,
    AlarmRuleResponseFromJSON,
    AlarmRuleResponseToJSON,
    AlarmRuleStatsRequestFromJSON,
    AlarmRuleStatsRequestToJSON,
    AlarmRuleStatsResponseFromJSON,
    AlarmRuleStatsResponseToJSON,
    CreateAlarmRuleRequestFromJSON,
    CreateAlarmRuleRequestToJSON,
    UpdateAlarmRuleRequestFromJSON,
    UpdateAlarmRuleRequestToJSON,
} from '../models/index';

export interface AlarmRuleStatsOperationRequest {
    alarmRuleStatsRequest: AlarmRuleStatsRequest;
}

export interface CreateAlarmRuleOperationRequest {
    createAlarmRuleRequest: CreateAlarmRuleRequest;
}

export interface DeleteAlarmRuleRequest {
    ruleId: number;
}

export interface DisableAlarmRuleRequest {
    ruleId: number;
}

export interface EnableAlarmRuleRequest {
    ruleId: number;
}

export interface GetAlarmRuleRequest {
    ruleId: number;
}

export interface PreviewAlarmRuleRequest {
    alarmRulePreviewRequest: AlarmRulePreviewRequest;
}

export interface UpdateAlarmRuleOperationRequest {
    ruleId: number;
    updateAlarmRuleRequest: UpdateAlarmRuleRequest;
}

/**
 * 
 */
export class AlarmRulesApi extends runtime.BaseAPI {

    /**
     */
    async alarmRuleStatsRaw(requestParameters: AlarmRuleStatsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlarmRuleStatsResponse>> {
        if (requestParameters['alarmRuleStatsRequest'] == null) {
            throw new runtime.RequiredError(
                'alarmRuleStatsRequest',
                'Required parameter "alarmRuleStatsRequest" was null or undefined when calling alarmRuleStats().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarm-rules/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlarmRuleStatsRequestToJSON(requestParameters['alarmRuleStatsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlarmRuleStatsResponseFromJSON(jsonValue));
    }

    /**
     */
    async alarmRuleStats(requestParameters: AlarmRuleStatsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlarmRuleStatsResponse> {
        const response = await this.alarmRuleStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createAlarmRuleRaw(requestParameters: CreateAlarmRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlarmRuleResponse>> {
        if (requestParameters['createAlarmRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'createAlarmRuleRequest',
                'Required parameter "createAlarmRuleRequest" was null or undefined when calling createAlarmRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarm-rules`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAlarmRuleRequestToJSON(requestParameters['createAlarmRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlarmRuleResponseFromJSON(jsonValue));
    }

    /**
     */
    async createAlarmRule(requestParameters: CreateAlarmRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlarmRuleResponse> {
        const response = await this.createAlarmRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteAlarmRuleRaw(requestParameters: DeleteAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlarmRuleDeleteResponse>> {
        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling deleteAlarmRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarm-rules/{rule_id}`;
        urlPath = urlPath.replace(`{${"rule_id"}}`, encodeURIComponent(String(requestParameters['ruleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlarmRuleDeleteResponseFromJSON(jsonValue));
    }

    /**
     */
    async deleteAlarmRule(requestParameters: DeleteAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlarmRuleDeleteResponse> {
        const response = await this.deleteAlarmRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async disableAlarmRuleRaw(requestParameters: DisableAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlarmRuleResponse>> {
        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling disableAlarmRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarm-rules/{rule_id}/disable`;
        urlPath = urlPath.replace(`{${"rule_id"}}`, encodeURIComponent(String(requestParameters['ruleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlarmRuleResponseFromJSON(jsonValue));
    }

    /**
     */
    async disableAlarmRule(requestParameters: DisableAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlarmRuleResponse> {
        const response = await this.disableAlarmRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async enableAlarmRuleRaw(requestParameters: EnableAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlarmRuleResponse>> {
        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling enableAlarmRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarm-rules/{rule_id}/enable`;
        urlPath = urlPath.replace(`{${"rule_id"}}`, encodeURIComponent(String(requestParameters['ruleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlarmRuleResponseFromJSON(jsonValue));
    }

    /**
     */
    async enableAlarmRule(requestParameters: EnableAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlarmRuleResponse> {
        const response = await this.enableAlarmRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAlarmRuleRaw(requestParameters: GetAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlarmRuleResponse>> {
        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling getAlarmRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarm-rules/{rule_id}`;
        urlPath = urlPath.replace(`{${"rule_id"}}`, encodeURIComponent(String(requestParameters['ruleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlarmRuleResponseFromJSON(jsonValue));
    }

    /**
     */
    async getAlarmRule(requestParameters: GetAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlarmRuleResponse> {
        const response = await this.getAlarmRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listAlarmRulesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlarmRuleResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarm-rules`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlarmRuleResponseFromJSON));
    }

    /**
     */
    async listAlarmRules(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlarmRuleResponse>> {
        const response = await this.listAlarmRulesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async previewAlarmRuleRaw(requestParameters: PreviewAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlarmRulePreviewResponse>> {
        if (requestParameters['alarmRulePreviewRequest'] == null) {
            throw new runtime.RequiredError(
                'alarmRulePreviewRequest',
                'Required parameter "alarmRulePreviewRequest" was null or undefined when calling previewAlarmRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarm-rules/preview`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlarmRulePreviewRequestToJSON(requestParameters['alarmRulePreviewRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlarmRulePreviewResponseFromJSON(jsonValue));
    }

    /**
     */
    async previewAlarmRule(requestParameters: PreviewAlarmRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlarmRulePreviewResponse> {
        const response = await this.previewAlarmRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateAlarmRuleRaw(requestParameters: UpdateAlarmRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlarmRuleResponse>> {
        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling updateAlarmRule().'
            );
        }

        if (requestParameters['updateAlarmRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAlarmRuleRequest',
                'Required parameter "updateAlarmRuleRequest" was null or undefined when calling updateAlarmRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarm-rules/{rule_id}`;
        urlPath = urlPath.replace(`{${"rule_id"}}`, encodeURIComponent(String(requestParameters['ruleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAlarmRuleRequestToJSON(requestParameters['updateAlarmRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlarmRuleResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateAlarmRule(requestParameters: UpdateAlarmRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlarmRuleResponse> {
        const response = await this.updateAlarmRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
