/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlarmEventResponse,
  AlarmResponse,
  BulkAcknowledgeRequest,
  BulkAcknowledgeResponse,
} from '../models/index';
import {
    AlarmEventResponseFromJSON,
    AlarmEventResponseToJSON,
    AlarmResponseFromJSON,
    AlarmResponseToJSON,
    BulkAcknowledgeRequestFromJSON,
    BulkAcknowledgeRequestToJSON,
    BulkAcknowledgeResponseFromJSON,
    BulkAcknowledgeResponseToJSON,
} from '../models/index';

export interface AcknowledgeEventRequest {
    eventId: string;
}

export interface AcknowledgeEventsBulkRequest {
    bulkAcknowledgeRequest: BulkAcknowledgeRequest;
}

export interface AlarmHistoryRequest {
    limit?: number | null;
}

/**
 * 
 */
export class AlarmsApi extends runtime.BaseAPI {

    /**
     * Creates request options for acknowledgeEvent without sending the request
     */
    async acknowledgeEventRequestOpts(requestParameters: AcknowledgeEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling acknowledgeEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/alarms/events/{event_id}/ack`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async acknowledgeEventRaw(requestParameters: AcknowledgeEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlarmEventResponse>> {
        const requestOptions = await this.acknowledgeEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlarmEventResponseFromJSON(jsonValue));
    }

    /**
     */
    async acknowledgeEvent(requestParameters: AcknowledgeEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlarmEventResponse> {
        const response = await this.acknowledgeEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for acknowledgeEventsBulk without sending the request
     */
    async acknowledgeEventsBulkRequestOpts(requestParameters: AcknowledgeEventsBulkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bulkAcknowledgeRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkAcknowledgeRequest',
                'Required parameter "bulkAcknowledgeRequest" was null or undefined when calling acknowledgeEventsBulk().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarms/events/ack-bulk`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkAcknowledgeRequestToJSON(requestParameters['bulkAcknowledgeRequest']),
        };
    }

    /**
     */
    async acknowledgeEventsBulkRaw(requestParameters: AcknowledgeEventsBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkAcknowledgeResponse>> {
        const requestOptions = await this.acknowledgeEventsBulkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkAcknowledgeResponseFromJSON(jsonValue));
    }

    /**
     */
    async acknowledgeEventsBulk(requestParameters: AcknowledgeEventsBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkAcknowledgeResponse> {
        const response = await this.acknowledgeEventsBulkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for alarmHistory without sending the request
     */
    async alarmHistoryRequestOpts(requestParameters: AlarmHistoryRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarms/history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async alarmHistoryRaw(requestParameters: AlarmHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlarmEventResponse>>> {
        const requestOptions = await this.alarmHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlarmEventResponseFromJSON));
    }

    /**
     */
    async alarmHistory(requestParameters: AlarmHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlarmEventResponse>> {
        const response = await this.alarmHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAlarms without sending the request
     */
    async listAlarmsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alarms`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listAlarmsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlarmResponse>>> {
        const requestOptions = await this.listAlarmsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlarmResponseFromJSON));
    }

    /**
     */
    async listAlarms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlarmResponse>> {
        const response = await this.listAlarmsRaw(initOverrides);
        return await response.value();
    }

}
