/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnalysisJobCancelResponse,
  AnalysisJobCreateRequest,
  AnalysisJobCreateResponse,
  AnalysisJobEventsResponse,
  AnalysisJobResultResponse,
  AnalysisJobStatusResponse,
  TssePreviewRequestV1,
  TssePreviewResponseV1,
} from '../models/index';
import {
    AnalysisJobCancelResponseFromJSON,
    AnalysisJobCancelResponseToJSON,
    AnalysisJobCreateRequestFromJSON,
    AnalysisJobCreateRequestToJSON,
    AnalysisJobCreateResponseFromJSON,
    AnalysisJobCreateResponseToJSON,
    AnalysisJobEventsResponseFromJSON,
    AnalysisJobEventsResponseToJSON,
    AnalysisJobResultResponseFromJSON,
    AnalysisJobResultResponseToJSON,
    AnalysisJobStatusResponseFromJSON,
    AnalysisJobStatusResponseToJSON,
    TssePreviewRequestV1FromJSON,
    TssePreviewRequestV1ToJSON,
    TssePreviewResponseV1FromJSON,
    TssePreviewResponseV1ToJSON,
} from '../models/index';

export interface CancelJobRequest {
    id: string;
}

export interface CreateJobRequest {
    analysisJobCreateRequest: AnalysisJobCreateRequest;
}

export interface GetJobRequest {
    id: string;
}

export interface GetJobEventsRequest {
    id: string;
    after?: number | null;
    limit?: number | null;
}

export interface GetJobResultRequest {
    id: string;
}

export interface PreviewRequest {
    tssePreviewRequestV1: TssePreviewRequestV1;
}

/**
 * 
 */
export class AnalysisApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelJob without sending the request
     */
    async cancelJobRequestOpts(requestParameters: CancelJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/analysis/jobs/{id}/cancel`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async cancelJobRaw(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalysisJobCancelResponse>> {
        const requestOptions = await this.cancelJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalysisJobCancelResponseFromJSON(jsonValue));
    }

    /**
     */
    async cancelJob(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalysisJobCancelResponse> {
        const response = await this.cancelJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createJob without sending the request
     */
    async createJobRequestOpts(requestParameters: CreateJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['analysisJobCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'analysisJobCreateRequest',
                'Required parameter "analysisJobCreateRequest" was null or undefined when calling createJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/analysis/jobs`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AnalysisJobCreateRequestToJSON(requestParameters['analysisJobCreateRequest']),
        };
    }

    /**
     */
    async createJobRaw(requestParameters: CreateJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalysisJobCreateResponse>> {
        const requestOptions = await this.createJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalysisJobCreateResponseFromJSON(jsonValue));
    }

    /**
     */
    async createJob(requestParameters: CreateJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalysisJobCreateResponse> {
        const response = await this.createJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getJob without sending the request
     */
    async getJobRequestOpts(requestParameters: GetJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/analysis/jobs/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getJobRaw(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalysisJobStatusResponse>> {
        const requestOptions = await this.getJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalysisJobStatusResponseFromJSON(jsonValue));
    }

    /**
     */
    async getJob(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalysisJobStatusResponse> {
        const response = await this.getJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getJobEvents without sending the request
     */
    async getJobEventsRequestOpts(requestParameters: GetJobEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getJobEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/analysis/jobs/{id}/events`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getJobEventsRaw(requestParameters: GetJobEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalysisJobEventsResponse>> {
        const requestOptions = await this.getJobEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalysisJobEventsResponseFromJSON(jsonValue));
    }

    /**
     */
    async getJobEvents(requestParameters: GetJobEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalysisJobEventsResponse> {
        const response = await this.getJobEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getJobResult without sending the request
     */
    async getJobResultRequestOpts(requestParameters: GetJobResultRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getJobResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/analysis/jobs/{id}/result`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getJobResultRaw(requestParameters: GetJobResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalysisJobResultResponse>> {
        const requestOptions = await this.getJobResultRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalysisJobResultResponseFromJSON(jsonValue));
    }

    /**
     */
    async getJobResult(requestParameters: GetJobResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalysisJobResultResponse> {
        const response = await this.getJobResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for preview without sending the request
     */
    async previewRequestOpts(requestParameters: PreviewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tssePreviewRequestV1'] == null) {
            throw new runtime.RequiredError(
                'tssePreviewRequestV1',
                'Required parameter "tssePreviewRequestV1" was null or undefined when calling preview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/analysis/preview`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TssePreviewRequestV1ToJSON(requestParameters['tssePreviewRequestV1']),
        };
    }

    /**
     */
    async previewRaw(requestParameters: PreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TssePreviewResponseV1>> {
        const requestOptions = await this.previewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TssePreviewResponseV1FromJSON(jsonValue));
    }

    /**
     */
    async preview(requestParameters: PreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TssePreviewResponseV1> {
        const response = await this.previewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
