/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnnotationResponse,
  CreateAnnotationRequest,
  UpdateAnnotationRequest,
} from '../models/index';
import {
    AnnotationResponseFromJSON,
    AnnotationResponseToJSON,
    CreateAnnotationRequestFromJSON,
    CreateAnnotationRequestToJSON,
    UpdateAnnotationRequestFromJSON,
    UpdateAnnotationRequestToJSON,
} from '../models/index';

export interface CreateAnnotationOperationRequest {
    createAnnotationRequest: CreateAnnotationRequest;
}

export interface DeleteAnnotationRequest {
    id: string;
}

export interface UpdateAnnotationOperationRequest {
    id: string;
    updateAnnotationRequest: UpdateAnnotationRequest;
}

/**
 * 
 */
export class ChartAnnotationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAnnotation without sending the request
     */
    async createAnnotationRequestOpts(requestParameters: CreateAnnotationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createAnnotationRequest'] == null) {
            throw new runtime.RequiredError(
                'createAnnotationRequest',
                'Required parameter "createAnnotationRequest" was null or undefined when calling createAnnotation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chart-annotations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAnnotationRequestToJSON(requestParameters['createAnnotationRequest']),
        };
    }

    /**
     */
    async createAnnotationRaw(requestParameters: CreateAnnotationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnnotationResponse>> {
        const requestOptions = await this.createAnnotationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnnotationResponseFromJSON(jsonValue));
    }

    /**
     */
    async createAnnotation(requestParameters: CreateAnnotationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnnotationResponse> {
        const response = await this.createAnnotationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAnnotation without sending the request
     */
    async deleteAnnotationRequestOpts(requestParameters: DeleteAnnotationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAnnotation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chart-annotations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteAnnotationRaw(requestParameters: DeleteAnnotationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteAnnotationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteAnnotation(requestParameters: DeleteAnnotationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAnnotationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listAnnotations without sending the request
     */
    async listAnnotationsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/chart-annotations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listAnnotationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AnnotationResponse>>> {
        const requestOptions = await this.listAnnotationsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AnnotationResponseFromJSON));
    }

    /**
     */
    async listAnnotations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AnnotationResponse>> {
        const response = await this.listAnnotationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAnnotation without sending the request
     */
    async updateAnnotationRequestOpts(requestParameters: UpdateAnnotationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAnnotation().'
            );
        }

        if (requestParameters['updateAnnotationRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAnnotationRequest',
                'Required parameter "updateAnnotationRequest" was null or undefined when calling updateAnnotation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chart-annotations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAnnotationRequestToJSON(requestParameters['updateAnnotationRequest']),
        };
    }

    /**
     */
    async updateAnnotationRaw(requestParameters: UpdateAnnotationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnnotationResponse>> {
        const requestOptions = await this.updateAnnotationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnnotationResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateAnnotation(requestParameters: UpdateAnnotationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnnotationResponse> {
        const response = await this.updateAnnotationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
