/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DevActivityHeartbeatRequest,
  DevActivityStatusResponse,
} from '../models/index';
import {
    DevActivityHeartbeatRequestFromJSON,
    DevActivityHeartbeatRequestToJSON,
    DevActivityStatusResponseFromJSON,
    DevActivityStatusResponseToJSON,
} from '../models/index';

export interface HeartbeatDevActivityRequest {
    devActivityHeartbeatRequest: DevActivityHeartbeatRequest;
}

/**
 * 
 */
export class DevApi extends runtime.BaseAPI {

    /**
     */
    async clearDevActivityRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/dev/activity`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async clearDevActivity(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.clearDevActivityRaw(initOverrides);
    }

    /**
     */
    async getDevActivityStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DevActivityStatusResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/dev/activity`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DevActivityStatusResponseFromJSON(jsonValue));
    }

    /**
     */
    async getDevActivityStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DevActivityStatusResponse> {
        const response = await this.getDevActivityStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async heartbeatDevActivityRaw(requestParameters: HeartbeatDevActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DevActivityStatusResponse>> {
        if (requestParameters['devActivityHeartbeatRequest'] == null) {
            throw new runtime.RequiredError(
                'devActivityHeartbeatRequest',
                'Required parameter "devActivityHeartbeatRequest" was null or undefined when calling heartbeatDevActivity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/dev/activity/heartbeat`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DevActivityHeartbeatRequestToJSON(requestParameters['devActivityHeartbeatRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DevActivityStatusResponseFromJSON(jsonValue));
    }

    /**
     */
    async heartbeatDevActivity(requestParameters: HeartbeatDevActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DevActivityStatusResponse> {
        const response = await this.heartbeatDevActivityRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
