/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExternalDeviceCatalogResponse,
  ExternalDeviceCreateRequest,
  ExternalDeviceSummary,
} from '../models/index';
import {
    ExternalDeviceCatalogResponseFromJSON,
    ExternalDeviceCatalogResponseToJSON,
    ExternalDeviceCreateRequestFromJSON,
    ExternalDeviceCreateRequestToJSON,
    ExternalDeviceSummaryFromJSON,
    ExternalDeviceSummaryToJSON,
} from '../models/index';

export interface CreateDeviceRequest {
    externalDeviceCreateRequest: ExternalDeviceCreateRequest;
}

export interface DeleteDeviceRequest {
    nodeId: string;
}

export interface SyncDeviceRequest {
    nodeId: string;
}

/**
 * 
 */
export class IntegrationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createDevice without sending the request
     */
    async createDeviceRequestOpts(requestParameters: CreateDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['externalDeviceCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'externalDeviceCreateRequest',
                'Required parameter "externalDeviceCreateRequest" was null or undefined when calling createDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/integrations/devices`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExternalDeviceCreateRequestToJSON(requestParameters['externalDeviceCreateRequest']),
        };
    }

    /**
     */
    async createDeviceRaw(requestParameters: CreateDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExternalDeviceSummary>> {
        const requestOptions = await this.createDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExternalDeviceSummaryFromJSON(jsonValue));
    }

    /**
     */
    async createDevice(requestParameters: CreateDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExternalDeviceSummary> {
        const response = await this.createDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteDevice without sending the request
     */
    async deleteDeviceRequestOpts(requestParameters: DeleteDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling deleteDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/integrations/devices/{node_id}`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteDeviceRaw(requestParameters: DeleteDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteDevice(requestParameters: DeleteDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDeviceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getDeviceCatalog without sending the request
     */
    async getDeviceCatalogRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/integrations/devices/catalog`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getDeviceCatalogRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExternalDeviceCatalogResponse>> {
        const requestOptions = await this.getDeviceCatalogRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExternalDeviceCatalogResponseFromJSON(jsonValue));
    }

    /**
     */
    async getDeviceCatalog(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExternalDeviceCatalogResponse> {
        const response = await this.getDeviceCatalogRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDevices without sending the request
     */
    async listDevicesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/integrations/devices`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listDevicesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExternalDeviceSummary>>> {
        const requestOptions = await this.listDevicesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExternalDeviceSummaryFromJSON));
    }

    /**
     */
    async listDevices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExternalDeviceSummary>> {
        const response = await this.listDevicesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for syncDevice without sending the request
     */
    async syncDeviceRequestOpts(requestParameters: SyncDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling syncDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/integrations/devices/{node_id}/sync`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async syncDeviceRaw(requestParameters: SyncDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.syncDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async syncDevice(requestParameters: SyncDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.syncDeviceRaw(requestParameters, initOverrides);
    }

}
