/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MetricIngestRequest,
  MetricIngestResponse,
  MetricsResponse,
} from '../models/index';
import {
    MetricIngestRequestFromJSON,
    MetricIngestRequestToJSON,
    MetricIngestResponseFromJSON,
    MetricIngestResponseToJSON,
    MetricsResponseFromJSON,
    MetricsResponseToJSON,
} from '../models/index';

export interface IngestMetricsRequest {
    metricIngestRequest: MetricIngestRequest;
}

export interface QueryMetricsRequest {
    sensorIds: Array<string>;
    start: string;
    end: string;
    interval?: number | null;
    cursor?: string | null;
    format?: string | null;
}

/**
 * 
 */
export class MetricsApi extends runtime.BaseAPI {

    /**
     */
    async ingestMetricsRaw(requestParameters: IngestMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetricIngestResponse>> {
        if (requestParameters['metricIngestRequest'] == null) {
            throw new runtime.RequiredError(
                'metricIngestRequest',
                'Required parameter "metricIngestRequest" was null or undefined when calling ingestMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/metrics/ingest`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetricIngestRequestToJSON(requestParameters['metricIngestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetricIngestResponseFromJSON(jsonValue));
    }

    /**
     */
    async ingestMetrics(requestParameters: IngestMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetricIngestResponse> {
        const response = await this.ingestMetricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async queryMetricsRaw(requestParameters: QueryMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetricsResponse>> {
        if (requestParameters['sensorIds'] == null) {
            throw new runtime.RequiredError(
                'sensorIds',
                'Required parameter "sensorIds" was null or undefined when calling queryMetrics().'
            );
        }

        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling queryMetrics().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling queryMetrics().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sensorIds'] != null) {
            queryParameters['sensor_ids'] = requestParameters['sensorIds'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/metrics/query`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetricsResponseFromJSON(jsonValue));
    }

    /**
     */
    async queryMetrics(requestParameters: QueryMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetricsResponse> {
        const response = await this.queryMetricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
