/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApplyNodeSensorsConfigResponse,
  ApplyRenogyBt2PresetRequest,
  ApplyRenogyBt2PresetResponse,
  NodeCreateRequest,
  NodeDisplayProfile,
  NodeOrderUpdateRequest,
  NodeResponse,
  NodeSensorsConfigResponse,
  NodeSensorsConfigUpdateRequest,
  NodeSensorsOrderUpdateRequest,
  NodeUpdateRequest,
  UpdateNodeDisplayProfileResponse,
} from '../models/index';
import {
    ApplyNodeSensorsConfigResponseFromJSON,
    ApplyNodeSensorsConfigResponseToJSON,
    ApplyRenogyBt2PresetRequestFromJSON,
    ApplyRenogyBt2PresetRequestToJSON,
    ApplyRenogyBt2PresetResponseFromJSON,
    ApplyRenogyBt2PresetResponseToJSON,
    NodeCreateRequestFromJSON,
    NodeCreateRequestToJSON,
    NodeDisplayProfileFromJSON,
    NodeDisplayProfileToJSON,
    NodeOrderUpdateRequestFromJSON,
    NodeOrderUpdateRequestToJSON,
    NodeResponseFromJSON,
    NodeResponseToJSON,
    NodeSensorsConfigResponseFromJSON,
    NodeSensorsConfigResponseToJSON,
    NodeSensorsConfigUpdateRequestFromJSON,
    NodeSensorsConfigUpdateRequestToJSON,
    NodeSensorsOrderUpdateRequestFromJSON,
    NodeSensorsOrderUpdateRequestToJSON,
    NodeUpdateRequestFromJSON,
    NodeUpdateRequestToJSON,
    UpdateNodeDisplayProfileResponseFromJSON,
    UpdateNodeDisplayProfileResponseToJSON,
} from '../models/index';

export interface ApplyRenogyBt2PresetOperationRequest {
    nodeId: string;
    applyRenogyBt2PresetRequest: ApplyRenogyBt2PresetRequest;
}

export interface CreateNodeRequest {
    nodeCreateRequest: NodeCreateRequest;
}

export interface DeleteNodeRequest {
    nodeId: string;
    purge?: boolean;
}

export interface GetNodeRequest {
    nodeId: string;
}

export interface GetNodeDisplayProfileRequest {
    nodeId: string;
}

export interface GetNodeSensorsConfigRequest {
    nodeId: string;
}

export interface UpdateNodeRequest {
    nodeId: string;
    nodeUpdateRequest: NodeUpdateRequest;
}

export interface UpdateNodeDisplayProfileRequest {
    nodeId: string;
    nodeDisplayProfile: NodeDisplayProfile;
}

export interface UpdateNodeOrderRequest {
    nodeOrderUpdateRequest: NodeOrderUpdateRequest;
}

export interface UpdateNodeSensorsConfigRequest {
    nodeId: string;
    nodeSensorsConfigUpdateRequest: NodeSensorsConfigUpdateRequest;
}

export interface UpdateNodeSensorsOrderRequest {
    nodeId: string;
    nodeSensorsOrderUpdateRequest: NodeSensorsOrderUpdateRequest;
}

/**
 * 
 */
export class NodesApi extends runtime.BaseAPI {

    /**
     */
    async applyRenogyBt2PresetRaw(requestParameters: ApplyRenogyBt2PresetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplyRenogyBt2PresetResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling applyRenogyBt2Preset().'
            );
        }

        if (requestParameters['applyRenogyBt2PresetRequest'] == null) {
            throw new runtime.RequiredError(
                'applyRenogyBt2PresetRequest',
                'Required parameter "applyRenogyBt2PresetRequest" was null or undefined when calling applyRenogyBt2Preset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/nodes/{node_id}/presets/renogy-bt2`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplyRenogyBt2PresetRequestToJSON(requestParameters['applyRenogyBt2PresetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplyRenogyBt2PresetResponseFromJSON(jsonValue));
    }

    /**
     */
    async applyRenogyBt2Preset(requestParameters: ApplyRenogyBt2PresetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplyRenogyBt2PresetResponse> {
        const response = await this.applyRenogyBt2PresetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createNodeRaw(requestParameters: CreateNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeResponse>> {
        if (requestParameters['nodeCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'nodeCreateRequest',
                'Required parameter "nodeCreateRequest" was null or undefined when calling createNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/nodes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodeCreateRequestToJSON(requestParameters['nodeCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeResponseFromJSON(jsonValue));
    }

    /**
     */
    async createNode(requestParameters: CreateNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeResponse> {
        const response = await this.createNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteNodeRaw(requestParameters: DeleteNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling deleteNode().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['purge'] != null) {
            queryParameters['purge'] = requestParameters['purge'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/nodes/{node_id}`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteNode(requestParameters: DeleteNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteNodeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getNodeRaw(requestParameters: GetNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling getNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/nodes/{node_id}`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeResponseFromJSON(jsonValue));
    }

    /**
     */
    async getNode(requestParameters: GetNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeResponse> {
        const response = await this.getNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getNodeDisplayProfileRaw(requestParameters: GetNodeDisplayProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeDisplayProfile>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling getNodeDisplayProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/nodes/{node_id}/display`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeDisplayProfileFromJSON(jsonValue));
    }

    /**
     */
    async getNodeDisplayProfile(requestParameters: GetNodeDisplayProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeDisplayProfile> {
        const response = await this.getNodeDisplayProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getNodeSensorsConfigRaw(requestParameters: GetNodeSensorsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeSensorsConfigResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling getNodeSensorsConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/nodes/{node_id}/sensors/config`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeSensorsConfigResponseFromJSON(jsonValue));
    }

    /**
     */
    async getNodeSensorsConfig(requestParameters: GetNodeSensorsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeSensorsConfigResponse> {
        const response = await this.getNodeSensorsConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listNodesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NodeResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/nodes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NodeResponseFromJSON));
    }

    /**
     */
    async listNodes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NodeResponse>> {
        const response = await this.listNodesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateNodeRaw(requestParameters: UpdateNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling updateNode().'
            );
        }

        if (requestParameters['nodeUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'nodeUpdateRequest',
                'Required parameter "nodeUpdateRequest" was null or undefined when calling updateNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/nodes/{node_id}`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NodeUpdateRequestToJSON(requestParameters['nodeUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateNode(requestParameters: UpdateNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeResponse> {
        const response = await this.updateNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateNodeDisplayProfileRaw(requestParameters: UpdateNodeDisplayProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateNodeDisplayProfileResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling updateNodeDisplayProfile().'
            );
        }

        if (requestParameters['nodeDisplayProfile'] == null) {
            throw new runtime.RequiredError(
                'nodeDisplayProfile',
                'Required parameter "nodeDisplayProfile" was null or undefined when calling updateNodeDisplayProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/nodes/{node_id}/display`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NodeDisplayProfileToJSON(requestParameters['nodeDisplayProfile']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateNodeDisplayProfileResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateNodeDisplayProfile(requestParameters: UpdateNodeDisplayProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateNodeDisplayProfileResponse> {
        const response = await this.updateNodeDisplayProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateNodeOrderRaw(requestParameters: UpdateNodeOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['nodeOrderUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'nodeOrderUpdateRequest',
                'Required parameter "nodeOrderUpdateRequest" was null or undefined when calling updateNodeOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/nodes/order`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NodeOrderUpdateRequestToJSON(requestParameters['nodeOrderUpdateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateNodeOrder(requestParameters: UpdateNodeOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateNodeOrderRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateNodeSensorsConfigRaw(requestParameters: UpdateNodeSensorsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplyNodeSensorsConfigResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling updateNodeSensorsConfig().'
            );
        }

        if (requestParameters['nodeSensorsConfigUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'nodeSensorsConfigUpdateRequest',
                'Required parameter "nodeSensorsConfigUpdateRequest" was null or undefined when calling updateNodeSensorsConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/nodes/{node_id}/sensors/config`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NodeSensorsConfigUpdateRequestToJSON(requestParameters['nodeSensorsConfigUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplyNodeSensorsConfigResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateNodeSensorsConfig(requestParameters: UpdateNodeSensorsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplyNodeSensorsConfigResponse> {
        const response = await this.updateNodeSensorsConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateNodeSensorsOrderRaw(requestParameters: UpdateNodeSensorsOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling updateNodeSensorsOrder().'
            );
        }

        if (requestParameters['nodeSensorsOrderUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'nodeSensorsOrderUpdateRequest',
                'Required parameter "nodeSensorsOrderUpdateRequest" was null or undefined when calling updateNodeSensorsOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/nodes/{node_id}/sensors/order`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NodeSensorsOrderUpdateRequestToJSON(requestParameters['nodeSensorsOrderUpdateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateNodeSensorsOrder(requestParameters: UpdateNodeSensorsOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateNodeSensorsOrderRaw(requestParameters, initOverrides);
    }

}
