/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PowerRunwayConfigRequest,
  PowerRunwayConfigResponse,
} from '../models/index';
import {
    PowerRunwayConfigRequestFromJSON,
    PowerRunwayConfigRequestToJSON,
    PowerRunwayConfigResponseFromJSON,
    PowerRunwayConfigResponseToJSON,
} from '../models/index';

export interface GetPowerRunwayConfigRequest {
    nodeId: string;
}

export interface PutPowerRunwayConfigRequest {
    nodeId: string;
    powerRunwayConfigRequest: PowerRunwayConfigRequest;
}

/**
 * 
 */
export class PowerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPowerRunwayConfig without sending the request
     */
    async getPowerRunwayConfigRequestOpts(requestParameters: GetPowerRunwayConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling getPowerRunwayConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/power/runway/config/{node_id}`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getPowerRunwayConfigRaw(requestParameters: GetPowerRunwayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PowerRunwayConfigResponse>> {
        const requestOptions = await this.getPowerRunwayConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PowerRunwayConfigResponseFromJSON(jsonValue));
    }

    /**
     */
    async getPowerRunwayConfig(requestParameters: GetPowerRunwayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PowerRunwayConfigResponse> {
        const response = await this.getPowerRunwayConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putPowerRunwayConfig without sending the request
     */
    async putPowerRunwayConfigRequestOpts(requestParameters: PutPowerRunwayConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling putPowerRunwayConfig().'
            );
        }

        if (requestParameters['powerRunwayConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'powerRunwayConfigRequest',
                'Required parameter "powerRunwayConfigRequest" was null or undefined when calling putPowerRunwayConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/power/runway/config/{node_id}`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PowerRunwayConfigRequestToJSON(requestParameters['powerRunwayConfigRequest']),
        };
    }

    /**
     */
    async putPowerRunwayConfigRaw(requestParameters: PutPowerRunwayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PowerRunwayConfigResponse>> {
        const requestOptions = await this.putPowerRunwayConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PowerRunwayConfigResponseFromJSON(jsonValue));
    }

    /**
     */
    async putPowerRunwayConfig(requestParameters: PutPowerRunwayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PowerRunwayConfigResponse> {
        const response = await this.putPowerRunwayConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
