/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RenogyApplyResponse,
  RenogyDesiredSettingsResponse,
  RenogyDesiredSettingsUpdateRequest,
  RenogyHistoryEntry,
  RenogyMaintenanceModeRequest,
  RenogyReadCurrentResponse,
  RenogyRegisterMapSchema,
  RenogyRollbackRequest,
  RenogyValidateResponse,
} from '../models/index';
import {
    RenogyApplyResponseFromJSON,
    RenogyApplyResponseToJSON,
    RenogyDesiredSettingsResponseFromJSON,
    RenogyDesiredSettingsResponseToJSON,
    RenogyDesiredSettingsUpdateRequestFromJSON,
    RenogyDesiredSettingsUpdateRequestToJSON,
    RenogyHistoryEntryFromJSON,
    RenogyHistoryEntryToJSON,
    RenogyMaintenanceModeRequestFromJSON,
    RenogyMaintenanceModeRequestToJSON,
    RenogyReadCurrentResponseFromJSON,
    RenogyReadCurrentResponseToJSON,
    RenogyRegisterMapSchemaFromJSON,
    RenogyRegisterMapSchemaToJSON,
    RenogyRollbackRequestFromJSON,
    RenogyRollbackRequestToJSON,
    RenogyValidateResponseFromJSON,
    RenogyValidateResponseToJSON,
} from '../models/index';

export interface ApplySettingsRequest {
    nodeId: string;
}

export interface GetDesiredSettingsRequest {
    nodeId: string;
}

export interface GetRegisterMapSchemaRequest {
    nodeId: string;
}

export interface ListHistoryRequest {
    nodeId: string;
}

export interface PutDesiredSettingsRequest {
    nodeId: string;
    renogyDesiredSettingsUpdateRequest: RenogyDesiredSettingsUpdateRequest;
}

export interface ReadCurrentSettingsRequest {
    nodeId: string;
}

export interface RollbackRequest {
    nodeId: string;
    renogyRollbackRequest: RenogyRollbackRequest;
}

export interface SetMaintenanceModeRequest {
    nodeId: string;
    renogyMaintenanceModeRequest: RenogyMaintenanceModeRequest;
}

export interface ValidateSettingsRequest {
    nodeId: string;
    renogyDesiredSettingsUpdateRequest: RenogyDesiredSettingsUpdateRequest;
}

/**
 * 
 */
export class RenogyApi extends runtime.BaseAPI {

    /**
     */
    async applySettingsRaw(requestParameters: ApplySettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenogyApplyResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling applySettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/nodes/{node_id}/renogy-bt2/settings/apply`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenogyApplyResponseFromJSON(jsonValue));
    }

    /**
     */
    async applySettings(requestParameters: ApplySettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenogyApplyResponse> {
        const response = await this.applySettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getDesiredSettingsRaw(requestParameters: GetDesiredSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenogyDesiredSettingsResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling getDesiredSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/nodes/{node_id}/renogy-bt2/settings/desired`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenogyDesiredSettingsResponseFromJSON(jsonValue));
    }

    /**
     */
    async getDesiredSettings(requestParameters: GetDesiredSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenogyDesiredSettingsResponse> {
        const response = await this.getDesiredSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRegisterMapSchemaRaw(requestParameters: GetRegisterMapSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenogyRegisterMapSchema>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling getRegisterMapSchema().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/nodes/{node_id}/renogy-bt2/settings/schema`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenogyRegisterMapSchemaFromJSON(jsonValue));
    }

    /**
     */
    async getRegisterMapSchema(requestParameters: GetRegisterMapSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenogyRegisterMapSchema> {
        const response = await this.getRegisterMapSchemaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listHistoryRaw(requestParameters: ListHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RenogyHistoryEntry>>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling listHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/nodes/{node_id}/renogy-bt2/settings/history`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RenogyHistoryEntryFromJSON));
    }

    /**
     */
    async listHistory(requestParameters: ListHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RenogyHistoryEntry>> {
        const response = await this.listHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async putDesiredSettingsRaw(requestParameters: PutDesiredSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenogyDesiredSettingsResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling putDesiredSettings().'
            );
        }

        if (requestParameters['renogyDesiredSettingsUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'renogyDesiredSettingsUpdateRequest',
                'Required parameter "renogyDesiredSettingsUpdateRequest" was null or undefined when calling putDesiredSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/nodes/{node_id}/renogy-bt2/settings/desired`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RenogyDesiredSettingsUpdateRequestToJSON(requestParameters['renogyDesiredSettingsUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenogyDesiredSettingsResponseFromJSON(jsonValue));
    }

    /**
     */
    async putDesiredSettings(requestParameters: PutDesiredSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenogyDesiredSettingsResponse> {
        const response = await this.putDesiredSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readCurrentSettingsRaw(requestParameters: ReadCurrentSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenogyReadCurrentResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling readCurrentSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/nodes/{node_id}/renogy-bt2/settings/read`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenogyReadCurrentResponseFromJSON(jsonValue));
    }

    /**
     */
    async readCurrentSettings(requestParameters: ReadCurrentSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenogyReadCurrentResponse> {
        const response = await this.readCurrentSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async rollbackRaw(requestParameters: RollbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenogyDesiredSettingsResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling rollback().'
            );
        }

        if (requestParameters['renogyRollbackRequest'] == null) {
            throw new runtime.RequiredError(
                'renogyRollbackRequest',
                'Required parameter "renogyRollbackRequest" was null or undefined when calling rollback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/nodes/{node_id}/renogy-bt2/settings/rollback`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RenogyRollbackRequestToJSON(requestParameters['renogyRollbackRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenogyDesiredSettingsResponseFromJSON(jsonValue));
    }

    /**
     */
    async rollback(requestParameters: RollbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenogyDesiredSettingsResponse> {
        const response = await this.rollbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async setMaintenanceModeRaw(requestParameters: SetMaintenanceModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenogyDesiredSettingsResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling setMaintenanceMode().'
            );
        }

        if (requestParameters['renogyMaintenanceModeRequest'] == null) {
            throw new runtime.RequiredError(
                'renogyMaintenanceModeRequest',
                'Required parameter "renogyMaintenanceModeRequest" was null or undefined when calling setMaintenanceMode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/nodes/{node_id}/renogy-bt2/settings/maintenance`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RenogyMaintenanceModeRequestToJSON(requestParameters['renogyMaintenanceModeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenogyDesiredSettingsResponseFromJSON(jsonValue));
    }

    /**
     */
    async setMaintenanceMode(requestParameters: SetMaintenanceModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenogyDesiredSettingsResponse> {
        const response = await this.setMaintenanceModeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async validateSettingsRaw(requestParameters: ValidateSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenogyValidateResponse>> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling validateSettings().'
            );
        }

        if (requestParameters['renogyDesiredSettingsUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'renogyDesiredSettingsUpdateRequest',
                'Required parameter "renogyDesiredSettingsUpdateRequest" was null or undefined when calling validateSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/nodes/{node_id}/renogy-bt2/settings/validate`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RenogyDesiredSettingsUpdateRequestToJSON(requestParameters['renogyDesiredSettingsUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenogyValidateResponseFromJSON(jsonValue));
    }

    /**
     */
    async validateSettings(requestParameters: ValidateSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenogyValidateResponse> {
        const response = await this.validateSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
