/* tslint:disable */
/* eslint-disable */
/**
 * Farm Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SensorCreateRequest,
  SensorResponse,
  SensorUpdateRequest,
} from '../models/index';
import {
    SensorCreateRequestFromJSON,
    SensorCreateRequestToJSON,
    SensorResponseFromJSON,
    SensorResponseToJSON,
    SensorUpdateRequestFromJSON,
    SensorUpdateRequestToJSON,
} from '../models/index';

export interface CreateSensorRequest {
    sensorCreateRequest: SensorCreateRequest;
}

export interface DeleteSensorRequest {
    sensorId: string;
    keepData?: boolean;
}

export interface GetSensorRequest {
    sensorId: string;
    includeHidden?: boolean;
}

export interface ListSensorsRequest {
    nodeId?: string | null;
    includeHidden?: boolean;
}

export interface UpdateSensorRequest {
    sensorId: string;
    sensorUpdateRequest: SensorUpdateRequest;
}

/**
 * 
 */
export class SensorsApi extends runtime.BaseAPI {

    /**
     */
    async createSensorRaw(requestParameters: CreateSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResponse>> {
        if (requestParameters['sensorCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'sensorCreateRequest',
                'Required parameter "sensorCreateRequest" was null or undefined when calling createSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/sensors`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SensorCreateRequestToJSON(requestParameters['sensorCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResponseFromJSON(jsonValue));
    }

    /**
     */
    async createSensor(requestParameters: CreateSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResponse> {
        const response = await this.createSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteSensorRaw(requestParameters: DeleteSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling deleteSensor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['keepData'] != null) {
            queryParameters['keep_data'] = requestParameters['keepData'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/sensors/{sensor_id}`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteSensor(requestParameters: DeleteSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSensorRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getSensorRaw(requestParameters: GetSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling getSensor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeHidden'] != null) {
            queryParameters['include_hidden'] = requestParameters['includeHidden'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sensors/{sensor_id}`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSensor(requestParameters: GetSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResponse> {
        const response = await this.getSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listSensorsRaw(requestParameters: ListSensorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SensorResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['nodeId'] != null) {
            queryParameters['node_id'] = requestParameters['nodeId'];
        }

        if (requestParameters['includeHidden'] != null) {
            queryParameters['include_hidden'] = requestParameters['includeHidden'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sensors`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SensorResponseFromJSON));
    }

    /**
     */
    async listSensors(requestParameters: ListSensorsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SensorResponse>> {
        const response = await this.listSensorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateSensorRaw(requestParameters: UpdateSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling updateSensor().'
            );
        }

        if (requestParameters['sensorUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'sensorUpdateRequest',
                'Required parameter "sensorUpdateRequest" was null or undefined when calling updateSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/sensors/{sensor_id}`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SensorUpdateRequestToJSON(requestParameters['sensorUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateSensor(requestParameters: UpdateSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResponse> {
        const response = await this.updateSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
