/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ControllerRuntimeConfigPatchRequest,
  ControllerRuntimeConfigResponse,
  EmporiaDevicesResponse,
  EmporiaDevicesUpdateRequest,
  EmporiaLoginRequest,
  EmporiaLoginResponse,
  MapillaryTokenResponse,
  SetupCredential,
  SetupCredentialsResponse,
  UpsertCredentialRequest,
} from '../models/index';
import {
    ControllerRuntimeConfigPatchRequestFromJSON,
    ControllerRuntimeConfigPatchRequestToJSON,
    ControllerRuntimeConfigResponseFromJSON,
    ControllerRuntimeConfigResponseToJSON,
    EmporiaDevicesResponseFromJSON,
    EmporiaDevicesResponseToJSON,
    EmporiaDevicesUpdateRequestFromJSON,
    EmporiaDevicesUpdateRequestToJSON,
    EmporiaLoginRequestFromJSON,
    EmporiaLoginRequestToJSON,
    EmporiaLoginResponseFromJSON,
    EmporiaLoginResponseToJSON,
    MapillaryTokenResponseFromJSON,
    MapillaryTokenResponseToJSON,
    SetupCredentialFromJSON,
    SetupCredentialToJSON,
    SetupCredentialsResponseFromJSON,
    SetupCredentialsResponseToJSON,
    UpsertCredentialRequestFromJSON,
    UpsertCredentialRequestToJSON,
} from '../models/index';

export interface DeleteCredentialRequest {
    name: string;
}

export interface EmporiaLoginOperationRequest {
    emporiaLoginRequest: EmporiaLoginRequest;
}

export interface EmporiaUpdateDevicesRequest {
    emporiaDevicesUpdateRequest: EmporiaDevicesUpdateRequest;
}

export interface PatchControllerRuntimeConfigRequest {
    controllerRuntimeConfigPatchRequest: ControllerRuntimeConfigPatchRequest;
}

export interface UpsertCredentialOperationRequest {
    name: string;
    upsertCredentialRequest: UpsertCredentialRequest;
}

/**
 * 
 */
export class SetupApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteCredential without sending the request
     */
    async deleteCredentialRequestOpts(requestParameters: DeleteCredentialRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/setup/credentials/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteCredentialRaw(requestParameters: DeleteCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteCredentialRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteCredential(requestParameters: DeleteCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCredentialRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for emporiaDevices without sending the request
     */
    async emporiaDevicesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/setup/emporia/devices`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async emporiaDevicesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmporiaDevicesResponse>> {
        const requestOptions = await this.emporiaDevicesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmporiaDevicesResponseFromJSON(jsonValue));
    }

    /**
     */
    async emporiaDevices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmporiaDevicesResponse> {
        const response = await this.emporiaDevicesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for emporiaLogin without sending the request
     */
    async emporiaLoginRequestOpts(requestParameters: EmporiaLoginOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emporiaLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'emporiaLoginRequest',
                'Required parameter "emporiaLoginRequest" was null or undefined when calling emporiaLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/setup/emporia/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmporiaLoginRequestToJSON(requestParameters['emporiaLoginRequest']),
        };
    }

    /**
     */
    async emporiaLoginRaw(requestParameters: EmporiaLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmporiaLoginResponse>> {
        const requestOptions = await this.emporiaLoginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmporiaLoginResponseFromJSON(jsonValue));
    }

    /**
     */
    async emporiaLogin(requestParameters: EmporiaLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmporiaLoginResponse> {
        const response = await this.emporiaLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for emporiaUpdateDevices without sending the request
     */
    async emporiaUpdateDevicesRequestOpts(requestParameters: EmporiaUpdateDevicesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emporiaDevicesUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'emporiaDevicesUpdateRequest',
                'Required parameter "emporiaDevicesUpdateRequest" was null or undefined when calling emporiaUpdateDevices().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/setup/emporia/devices`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EmporiaDevicesUpdateRequestToJSON(requestParameters['emporiaDevicesUpdateRequest']),
        };
    }

    /**
     */
    async emporiaUpdateDevicesRaw(requestParameters: EmporiaUpdateDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.emporiaUpdateDevicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async emporiaUpdateDevices(requestParameters: EmporiaUpdateDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.emporiaUpdateDevicesRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getControllerRuntimeConfig without sending the request
     */
    async getControllerRuntimeConfigRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/setup/controller/runtime-config`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getControllerRuntimeConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ControllerRuntimeConfigResponse>> {
        const requestOptions = await this.getControllerRuntimeConfigRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ControllerRuntimeConfigResponseFromJSON(jsonValue));
    }

    /**
     */
    async getControllerRuntimeConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ControllerRuntimeConfigResponse> {
        const response = await this.getControllerRuntimeConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMapillaryToken without sending the request
     */
    async getMapillaryTokenRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/setup/integrations/mapillary/token`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getMapillaryTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MapillaryTokenResponse>> {
        const requestOptions = await this.getMapillaryTokenRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MapillaryTokenResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMapillaryToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MapillaryTokenResponse> {
        const response = await this.getMapillaryTokenRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCredentials without sending the request
     */
    async listCredentialsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/setup/credentials`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listCredentialsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetupCredentialsResponse>> {
        const requestOptions = await this.listCredentialsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetupCredentialsResponseFromJSON(jsonValue));
    }

    /**
     */
    async listCredentials(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetupCredentialsResponse> {
        const response = await this.listCredentialsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchControllerRuntimeConfig without sending the request
     */
    async patchControllerRuntimeConfigRequestOpts(requestParameters: PatchControllerRuntimeConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['controllerRuntimeConfigPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'controllerRuntimeConfigPatchRequest',
                'Required parameter "controllerRuntimeConfigPatchRequest" was null or undefined when calling patchControllerRuntimeConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/setup/controller/runtime-config`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ControllerRuntimeConfigPatchRequestToJSON(requestParameters['controllerRuntimeConfigPatchRequest']),
        };
    }

    /**
     */
    async patchControllerRuntimeConfigRaw(requestParameters: PatchControllerRuntimeConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ControllerRuntimeConfigResponse>> {
        const requestOptions = await this.patchControllerRuntimeConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ControllerRuntimeConfigResponseFromJSON(jsonValue));
    }

    /**
     */
    async patchControllerRuntimeConfig(requestParameters: PatchControllerRuntimeConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ControllerRuntimeConfigResponse> {
        const response = await this.patchControllerRuntimeConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for upsertCredential without sending the request
     */
    async upsertCredentialRequestOpts(requestParameters: UpsertCredentialOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling upsertCredential().'
            );
        }

        if (requestParameters['upsertCredentialRequest'] == null) {
            throw new runtime.RequiredError(
                'upsertCredentialRequest',
                'Required parameter "upsertCredentialRequest" was null or undefined when calling upsertCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/setup/credentials/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpsertCredentialRequestToJSON(requestParameters['upsertCredentialRequest']),
        };
    }

    /**
     */
    async upsertCredentialRaw(requestParameters: UpsertCredentialOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetupCredential>> {
        const requestOptions = await this.upsertCredentialRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetupCredentialFromJSON(jsonValue));
    }

    /**
     */
    async upsertCredential(requestParameters: UpsertCredentialOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetupCredential> {
        const response = await this.upsertCredentialRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
