/* tslint:disable */
/* eslint-disable */
/**
 * Infrastructure Dashboard Core Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Ws2902CreateRequest,
  Ws2902CreateResponse,
  Ws2902RotateTokenResponse,
  Ws2902StatusResponse,
  Ws2902UpdateRequest,
} from '../models/index';
import {
    Ws2902CreateRequestFromJSON,
    Ws2902CreateRequestToJSON,
    Ws2902CreateResponseFromJSON,
    Ws2902CreateResponseToJSON,
    Ws2902RotateTokenResponseFromJSON,
    Ws2902RotateTokenResponseToJSON,
    Ws2902StatusResponseFromJSON,
    Ws2902StatusResponseToJSON,
    Ws2902UpdateRequestFromJSON,
    Ws2902UpdateRequestToJSON,
} from '../models/index';

export interface CreateWs2902Request {
    ws2902CreateRequest: Ws2902CreateRequest;
}

export interface GetWs2902StatusRequest {
    integrationId: string;
}

export interface GetWs2902StatusForNodeRequest {
    nodeId: string;
}

export interface IngestWs2902Request {
    token: string;
}

export interface IngestWsShortRequest {
    token: string;
}

export interface RotateWs2902TokenRequest {
    integrationId: string;
}

export interface RotateWs2902TokenForNodeRequest {
    nodeId: string;
}

export interface UpdateWs2902Request {
    integrationId: string;
    ws2902UpdateRequest: Ws2902UpdateRequest;
}

/**
 * 
 */
export class WeatherStationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createWs2902 without sending the request
     */
    async createWs2902RequestOpts(requestParameters: CreateWs2902Request): Promise<runtime.RequestOpts> {
        if (requestParameters['ws2902CreateRequest'] == null) {
            throw new runtime.RequiredError(
                'ws2902CreateRequest',
                'Required parameter "ws2902CreateRequest" was null or undefined when calling createWs2902().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/weather-stations/ws-2902`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: Ws2902CreateRequestToJSON(requestParameters['ws2902CreateRequest']),
        };
    }

    /**
     */
    async createWs2902Raw(requestParameters: CreateWs2902Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ws2902CreateResponse>> {
        const requestOptions = await this.createWs2902RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Ws2902CreateResponseFromJSON(jsonValue));
    }

    /**
     */
    async createWs2902(requestParameters: CreateWs2902Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ws2902CreateResponse> {
        const response = await this.createWs2902Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWs2902Status without sending the request
     */
    async getWs2902StatusRequestOpts(requestParameters: GetWs2902StatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['integrationId'] == null) {
            throw new runtime.RequiredError(
                'integrationId',
                'Required parameter "integrationId" was null or undefined when calling getWs2902Status().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather-stations/ws-2902/{integration_id}`;
        urlPath = urlPath.replace(`{${"integration_id"}}`, encodeURIComponent(String(requestParameters['integrationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getWs2902StatusRaw(requestParameters: GetWs2902StatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ws2902StatusResponse>> {
        const requestOptions = await this.getWs2902StatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Ws2902StatusResponseFromJSON(jsonValue));
    }

    /**
     */
    async getWs2902Status(requestParameters: GetWs2902StatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ws2902StatusResponse> {
        const response = await this.getWs2902StatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWs2902StatusForNode without sending the request
     */
    async getWs2902StatusForNodeRequestOpts(requestParameters: GetWs2902StatusForNodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling getWs2902StatusForNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather-stations/ws-2902/node/{node_id}`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getWs2902StatusForNodeRaw(requestParameters: GetWs2902StatusForNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ws2902StatusResponse>> {
        const requestOptions = await this.getWs2902StatusForNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Ws2902StatusResponseFromJSON(jsonValue));
    }

    /**
     */
    async getWs2902StatusForNode(requestParameters: GetWs2902StatusForNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ws2902StatusResponse> {
        const response = await this.getWs2902StatusForNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestWs2902 without sending the request
     */
    async ingestWs2902RequestOpts(requestParameters: IngestWs2902Request): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling ingestWs2902().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather-stations/ws-2902/ingest/{token}`;
        urlPath = urlPath.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async ingestWs2902Raw(requestParameters: IngestWs2902Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestWs2902RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async ingestWs2902(requestParameters: IngestWs2902Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestWs2902Raw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for ingestWsShort without sending the request
     */
    async ingestWsShortRequestOpts(requestParameters: IngestWsShortRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling ingestWsShort().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ws/{token}`;
        urlPath = urlPath.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async ingestWsShortRaw(requestParameters: IngestWsShortRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestWsShortRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async ingestWsShort(requestParameters: IngestWsShortRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestWsShortRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for rotateWs2902Token without sending the request
     */
    async rotateWs2902TokenRequestOpts(requestParameters: RotateWs2902TokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['integrationId'] == null) {
            throw new runtime.RequiredError(
                'integrationId',
                'Required parameter "integrationId" was null or undefined when calling rotateWs2902Token().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather-stations/ws-2902/{integration_id}/rotate-token`;
        urlPath = urlPath.replace(`{${"integration_id"}}`, encodeURIComponent(String(requestParameters['integrationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async rotateWs2902TokenRaw(requestParameters: RotateWs2902TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ws2902RotateTokenResponse>> {
        const requestOptions = await this.rotateWs2902TokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Ws2902RotateTokenResponseFromJSON(jsonValue));
    }

    /**
     */
    async rotateWs2902Token(requestParameters: RotateWs2902TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ws2902RotateTokenResponse> {
        const response = await this.rotateWs2902TokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rotateWs2902TokenForNode without sending the request
     */
    async rotateWs2902TokenForNodeRequestOpts(requestParameters: RotateWs2902TokenForNodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling rotateWs2902TokenForNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather-stations/ws-2902/node/{node_id}/rotate-token`;
        urlPath = urlPath.replace(`{${"node_id"}}`, encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async rotateWs2902TokenForNodeRaw(requestParameters: RotateWs2902TokenForNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ws2902RotateTokenResponse>> {
        const requestOptions = await this.rotateWs2902TokenForNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Ws2902RotateTokenResponseFromJSON(jsonValue));
    }

    /**
     */
    async rotateWs2902TokenForNode(requestParameters: RotateWs2902TokenForNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ws2902RotateTokenResponse> {
        const response = await this.rotateWs2902TokenForNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateWs2902 without sending the request
     */
    async updateWs2902RequestOpts(requestParameters: UpdateWs2902Request): Promise<runtime.RequestOpts> {
        if (requestParameters['integrationId'] == null) {
            throw new runtime.RequiredError(
                'integrationId',
                'Required parameter "integrationId" was null or undefined when calling updateWs2902().'
            );
        }

        if (requestParameters['ws2902UpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'ws2902UpdateRequest',
                'Required parameter "ws2902UpdateRequest" was null or undefined when calling updateWs2902().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/weather-stations/ws-2902/{integration_id}`;
        urlPath = urlPath.replace(`{${"integration_id"}}`, encodeURIComponent(String(requestParameters['integrationId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: Ws2902UpdateRequestToJSON(requestParameters['ws2902UpdateRequest']),
        };
    }

    /**
     */
    async updateWs2902Raw(requestParameters: UpdateWs2902Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ws2902StatusResponse>> {
        const requestOptions = await this.updateWs2902RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Ws2902StatusResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateWs2902(requestParameters: UpdateWs2902Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ws2902StatusResponse> {
        const response = await this.updateWs2902Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
