# coding: utf-8

"""
    Farm Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from generated_api.models.alarm_rule_stats_bands import AlarmRuleStatsBands
from typing import Optional, Set
from typing_extensions import Self

class AlarmRuleStatsSensorResponse(BaseModel):
    """
    AlarmRuleStatsSensorResponse
    """ # noqa: E501
    bands: AlarmRuleStatsBands
    coverage_pct: Optional[Union[StrictFloat, StrictInt]] = None
    interval_seconds: StrictInt
    iqr: Optional[Union[StrictFloat, StrictInt]] = None
    mad: Optional[Union[StrictFloat, StrictInt]] = None
    max: Optional[Union[StrictFloat, StrictInt]] = None
    mean: Optional[Union[StrictFloat, StrictInt]] = None
    median: Optional[Union[StrictFloat, StrictInt]] = None
    min: Optional[Union[StrictFloat, StrictInt]] = None
    missing_pct: Optional[Union[StrictFloat, StrictInt]] = None
    n: Annotated[int, Field(strict=True, ge=0)]
    p01: Optional[Union[StrictFloat, StrictInt]] = None
    p05: Optional[Union[StrictFloat, StrictInt]] = None
    p25: Optional[Union[StrictFloat, StrictInt]] = None
    p75: Optional[Union[StrictFloat, StrictInt]] = None
    p95: Optional[Union[StrictFloat, StrictInt]] = None
    p99: Optional[Union[StrictFloat, StrictInt]] = None
    sensor_id: StrictStr
    stddev: Optional[Union[StrictFloat, StrictInt]] = None
    unit: StrictStr
    __properties: ClassVar[List[str]] = ["bands", "coverage_pct", "interval_seconds", "iqr", "mad", "max", "mean", "median", "min", "missing_pct", "n", "p01", "p05", "p25", "p75", "p95", "p99", "sensor_id", "stddev", "unit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlarmRuleStatsSensorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bands
        if self.bands:
            _dict['bands'] = self.bands.to_dict()
        # set to None if coverage_pct (nullable) is None
        # and model_fields_set contains the field
        if self.coverage_pct is None and "coverage_pct" in self.model_fields_set:
            _dict['coverage_pct'] = None

        # set to None if iqr (nullable) is None
        # and model_fields_set contains the field
        if self.iqr is None and "iqr" in self.model_fields_set:
            _dict['iqr'] = None

        # set to None if mad (nullable) is None
        # and model_fields_set contains the field
        if self.mad is None and "mad" in self.model_fields_set:
            _dict['mad'] = None

        # set to None if max (nullable) is None
        # and model_fields_set contains the field
        if self.max is None and "max" in self.model_fields_set:
            _dict['max'] = None

        # set to None if mean (nullable) is None
        # and model_fields_set contains the field
        if self.mean is None and "mean" in self.model_fields_set:
            _dict['mean'] = None

        # set to None if median (nullable) is None
        # and model_fields_set contains the field
        if self.median is None and "median" in self.model_fields_set:
            _dict['median'] = None

        # set to None if min (nullable) is None
        # and model_fields_set contains the field
        if self.min is None and "min" in self.model_fields_set:
            _dict['min'] = None

        # set to None if missing_pct (nullable) is None
        # and model_fields_set contains the field
        if self.missing_pct is None and "missing_pct" in self.model_fields_set:
            _dict['missing_pct'] = None

        # set to None if p01 (nullable) is None
        # and model_fields_set contains the field
        if self.p01 is None and "p01" in self.model_fields_set:
            _dict['p01'] = None

        # set to None if p05 (nullable) is None
        # and model_fields_set contains the field
        if self.p05 is None and "p05" in self.model_fields_set:
            _dict['p05'] = None

        # set to None if p25 (nullable) is None
        # and model_fields_set contains the field
        if self.p25 is None and "p25" in self.model_fields_set:
            _dict['p25'] = None

        # set to None if p75 (nullable) is None
        # and model_fields_set contains the field
        if self.p75 is None and "p75" in self.model_fields_set:
            _dict['p75'] = None

        # set to None if p95 (nullable) is None
        # and model_fields_set contains the field
        if self.p95 is None and "p95" in self.model_fields_set:
            _dict['p95'] = None

        # set to None if p99 (nullable) is None
        # and model_fields_set contains the field
        if self.p99 is None and "p99" in self.model_fields_set:
            _dict['p99'] = None

        # set to None if stddev (nullable) is None
        # and model_fields_set contains the field
        if self.stddev is None and "stddev" in self.model_fields_set:
            _dict['stddev'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlarmRuleStatsSensorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bands": AlarmRuleStatsBands.from_dict(obj["bands"]) if obj.get("bands") is not None else None,
            "coverage_pct": obj.get("coverage_pct"),
            "interval_seconds": obj.get("interval_seconds"),
            "iqr": obj.get("iqr"),
            "mad": obj.get("mad"),
            "max": obj.get("max"),
            "mean": obj.get("mean"),
            "median": obj.get("median"),
            "min": obj.get("min"),
            "missing_pct": obj.get("missing_pct"),
            "n": obj.get("n"),
            "p01": obj.get("p01"),
            "p05": obj.get("p05"),
            "p25": obj.get("p25"),
            "p75": obj.get("p75"),
            "p95": obj.get("p95"),
            "p99": obj.get("p99"),
            "sensor_id": obj.get("sensor_id"),
            "stddev": obj.get("stddev"),
            "unit": obj.get("unit")
        })
        return _obj


