# coding: utf-8

"""
    Farm Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from generated_api.models.analytics_feed_status_entry import AnalyticsFeedStatusEntry
from typing import Optional, Set
from typing_extensions import Self

class AnalyticsStatus(BaseModel):
    """
    AnalyticsStatus
    """ # noqa: E501
    alarms_last_168h: StrictInt
    battery_runtime_hours: Union[StrictFloat, StrictInt]
    battery_soc: StrictInt
    current_load_kw: Optional[Union[StrictFloat, StrictInt]] = None
    estimated_runtime_hours: Optional[Union[StrictFloat, StrictInt]] = None
    feeds: Optional[Dict[str, AnalyticsFeedStatusEntry]] = None
    last_updated: Optional[StrictStr] = None
    nodes_offline: StrictInt
    nodes_online: StrictInt
    remote_nodes_offline: Optional[StrictInt] = None
    remote_nodes_online: Optional[StrictInt] = None
    solar_kw: Union[StrictFloat, StrictInt]
    storage_capacity_kwh: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["alarms_last_168h", "battery_runtime_hours", "battery_soc", "current_load_kw", "estimated_runtime_hours", "feeds", "last_updated", "nodes_offline", "nodes_online", "remote_nodes_offline", "remote_nodes_online", "solar_kw", "storage_capacity_kwh"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyticsStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in feeds (dict)
        _field_dict = {}
        if self.feeds:
            for _key_feeds in self.feeds:
                if self.feeds[_key_feeds]:
                    _field_dict[_key_feeds] = self.feeds[_key_feeds].to_dict()
            _dict['feeds'] = _field_dict
        # set to None if last_updated (nullable) is None
        # and model_fields_set contains the field
        if self.last_updated is None and "last_updated" in self.model_fields_set:
            _dict['last_updated'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyticsStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alarms_last_168h": obj.get("alarms_last_168h"),
            "battery_runtime_hours": obj.get("battery_runtime_hours"),
            "battery_soc": obj.get("battery_soc"),
            "current_load_kw": obj.get("current_load_kw"),
            "estimated_runtime_hours": obj.get("estimated_runtime_hours"),
            "feeds": dict(
                (_k, AnalyticsFeedStatusEntry.from_dict(_v))
                for _k, _v in obj["feeds"].items()
            )
            if obj.get("feeds") is not None
            else None,
            "last_updated": obj.get("last_updated"),
            "nodes_offline": obj.get("nodes_offline"),
            "nodes_online": obj.get("nodes_online"),
            "remote_nodes_offline": obj.get("remote_nodes_offline"),
            "remote_nodes_online": obj.get("remote_nodes_online"),
            "solar_kw": obj.get("solar_kw"),
            "storage_capacity_kwh": obj.get("storage_capacity_kwh")
        })
        return _obj


