# coding: utf-8

"""
    Farm Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from generated_api.models.analytics_feed_history_entry import AnalyticsFeedHistoryEntry
from generated_api.models.analytics_feed_status_entry import AnalyticsFeedStatusEntry
from typing import Optional, Set
from typing_extensions import Self

class AnalyticsFeedStatusResponse(BaseModel):
    """
    AnalyticsFeedStatusResponse
    """ # noqa: E501
    enabled: StrictBool
    feeds: Optional[Dict[str, AnalyticsFeedStatusEntry]] = None
    history: Optional[List[AnalyticsFeedHistoryEntry]] = None
    __properties: ClassVar[List[str]] = ["enabled", "feeds", "history"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyticsFeedStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in feeds (dict)
        _field_dict = {}
        if self.feeds:
            for _key_feeds in self.feeds:
                if self.feeds[_key_feeds]:
                    _field_dict[_key_feeds] = self.feeds[_key_feeds].to_dict()
            _dict['feeds'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in history (list)
        _items = []
        if self.history:
            for _item_history in self.history:
                if _item_history:
                    _items.append(_item_history.to_dict())
            _dict['history'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyticsFeedStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "feeds": dict(
                (_k, AnalyticsFeedStatusEntry.from_dict(_v))
                for _k, _v in obj["feeds"].items()
            )
            if obj.get("feeds") is not None
            else None,
            "history": [AnalyticsFeedHistoryEntry.from_dict(_item) for _item in obj["history"]] if obj.get("history") is not None else None
        })
        return _obj


