# coding: utf-8

"""
    Infrastructure Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CloudSiteResponse(BaseModel):
    """
    CloudSiteResponse
    """ # noqa: E501
    created_at: Optional[StrictStr] = None
    enabled: StrictBool
    key_fingerprint: StrictStr
    last_ingested_at: Optional[StrictStr] = None
    last_metrics_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    last_payload_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    site_id: StrictStr
    site_name: StrictStr
    updated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_at", "enabled", "key_fingerprint", "last_ingested_at", "last_metrics_count", "last_payload_bytes", "site_id", "site_name", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CloudSiteResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if last_ingested_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_ingested_at is None and "last_ingested_at" in self.model_fields_set:
            _dict['last_ingested_at'] = None

        # set to None if last_metrics_count (nullable) is None
        # and model_fields_set contains the field
        if self.last_metrics_count is None and "last_metrics_count" in self.model_fields_set:
            _dict['last_metrics_count'] = None

        # set to None if last_payload_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.last_payload_bytes is None and "last_payload_bytes" in self.model_fields_set:
            _dict['last_payload_bytes'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CloudSiteResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "enabled": obj.get("enabled"),
            "key_fingerprint": obj.get("key_fingerprint"),
            "last_ingested_at": obj.get("last_ingested_at"),
            "last_metrics_count": obj.get("last_metrics_count"),
            "last_payload_bytes": obj.get("last_payload_bytes"),
            "site_id": obj.get("site_id"),
            "site_name": obj.get("site_name"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


