# coding: utf-8

"""
    Infrastructure Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class DevicePoint(BaseModel):
    """
    DevicePoint
    """ # noqa: E501
    bacnet_object: Optional[StrictStr] = None
    data_type: Optional[StrictStr] = None
    json_pointer: Optional[StrictStr] = None
    metric: StrictStr
    name: StrictStr
    oid: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    protocol: StrictStr
    register: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    scale: Optional[Union[StrictFloat, StrictInt]] = None
    sensor_type: StrictStr
    unit: StrictStr
    __properties: ClassVar[List[str]] = ["bacnet_object", "data_type", "json_pointer", "metric", "name", "oid", "path", "protocol", "register", "scale", "sensor_type", "unit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DevicePoint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if bacnet_object (nullable) is None
        # and model_fields_set contains the field
        if self.bacnet_object is None and "bacnet_object" in self.model_fields_set:
            _dict['bacnet_object'] = None

        # set to None if data_type (nullable) is None
        # and model_fields_set contains the field
        if self.data_type is None and "data_type" in self.model_fields_set:
            _dict['data_type'] = None

        # set to None if json_pointer (nullable) is None
        # and model_fields_set contains the field
        if self.json_pointer is None and "json_pointer" in self.model_fields_set:
            _dict['json_pointer'] = None

        # set to None if oid (nullable) is None
        # and model_fields_set contains the field
        if self.oid is None and "oid" in self.model_fields_set:
            _dict['oid'] = None

        # set to None if path (nullable) is None
        # and model_fields_set contains the field
        if self.path is None and "path" in self.model_fields_set:
            _dict['path'] = None

        # set to None if register (nullable) is None
        # and model_fields_set contains the field
        if self.register is None and "register" in self.model_fields_set:
            _dict['register'] = None

        # set to None if scale (nullable) is None
        # and model_fields_set contains the field
        if self.scale is None and "scale" in self.model_fields_set:
            _dict['scale'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DevicePoint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bacnet_object": obj.get("bacnet_object"),
            "data_type": obj.get("data_type"),
            "json_pointer": obj.get("json_pointer"),
            "metric": obj.get("metric"),
            "name": obj.get("name"),
            "oid": obj.get("oid"),
            "path": obj.get("path"),
            "protocol": obj.get("protocol"),
            "register": obj.get("register"),
            "scale": obj.get("scale"),
            "sensor_type": obj.get("sensor_type"),
            "unit": obj.get("unit")
        })
        return _obj


