# coding: utf-8

"""
    Infrastructure Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from generated_api.models.emporia_circuit_settings import EmporiaCircuitSettings
from typing import Optional, Set
from typing_extensions import Self

class EmporiaDeviceSettings(BaseModel):
    """
    EmporiaDeviceSettings
    """ # noqa: E501
    address: Optional[StrictStr] = None
    circuits: List[EmporiaCircuitSettings]
    device_gid: StrictStr
    enabled: StrictBool
    firmware: Optional[StrictStr] = None
    group_label: Optional[StrictStr] = None
    hidden: StrictBool
    include_in_power_summary: StrictBool
    model: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["address", "circuits", "device_gid", "enabled", "firmware", "group_label", "hidden", "include_in_power_summary", "model", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmporiaDeviceSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in circuits (list)
        _items = []
        if self.circuits:
            for _item_circuits in self.circuits:
                if _item_circuits:
                    _items.append(_item_circuits.to_dict())
            _dict['circuits'] = _items
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if firmware (nullable) is None
        # and model_fields_set contains the field
        if self.firmware is None and "firmware" in self.model_fields_set:
            _dict['firmware'] = None

        # set to None if group_label (nullable) is None
        # and model_fields_set contains the field
        if self.group_label is None and "group_label" in self.model_fields_set:
            _dict['group_label'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmporiaDeviceSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "circuits": [EmporiaCircuitSettings.from_dict(_item) for _item in obj["circuits"]] if obj.get("circuits") is not None else None,
            "device_gid": obj.get("device_gid"),
            "enabled": obj.get("enabled"),
            "firmware": obj.get("firmware"),
            "group_label": obj.get("group_label"),
            "hidden": obj.get("hidden"),
            "include_in_power_summary": obj.get("include_in_power_summary"),
            "model": obj.get("model"),
            "name": obj.get("name")
        })
        return _obj


