# coding: utf-8

"""
    Infrastructure Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class NodeResponse(BaseModel):
    """
    NodeResponse
    """ # noqa: E501
    config: Optional[Any] = None
    cpu_percent: Union[StrictFloat, StrictInt]
    created_at: Optional[StrictStr] = None
    id: StrictStr
    ip_last: Optional[StrictStr] = None
    last_seen: Optional[StrictStr] = None
    mac_eth: Optional[StrictStr] = None
    mac_wifi: Optional[StrictStr] = None
    memory_percent: Optional[Union[StrictFloat, StrictInt]] = None
    memory_used_bytes: Optional[StrictInt] = None
    mqtt_broker_rtt_jitter_ms: Optional[Union[StrictFloat, StrictInt]] = None
    mqtt_broker_rtt_ms: Optional[Union[StrictFloat, StrictInt]] = None
    name: StrictStr
    network_jitter_ms: Optional[Union[StrictFloat, StrictInt]] = None
    network_latency_ms: Optional[Union[StrictFloat, StrictInt]] = None
    ping_jitter_ms: Optional[Union[StrictFloat, StrictInt]] = None
    ping_ms: Optional[Union[StrictFloat, StrictInt]] = None
    ping_p50_30m_ms: Optional[Union[StrictFloat, StrictInt]] = None
    status: StrictStr
    storage_used_bytes: StrictInt
    uptime_percent_24h: Optional[Union[StrictFloat, StrictInt]] = None
    uptime_seconds: StrictInt
    __properties: ClassVar[List[str]] = ["config", "cpu_percent", "created_at", "id", "ip_last", "last_seen", "mac_eth", "mac_wifi", "memory_percent", "memory_used_bytes", "mqtt_broker_rtt_jitter_ms", "mqtt_broker_rtt_ms", "name", "network_jitter_ms", "network_latency_ms", "ping_jitter_ms", "ping_ms", "ping_p50_30m_ms", "status", "storage_used_bytes", "uptime_percent_24h", "uptime_seconds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if ip_last (nullable) is None
        # and model_fields_set contains the field
        if self.ip_last is None and "ip_last" in self.model_fields_set:
            _dict['ip_last'] = None

        # set to None if last_seen (nullable) is None
        # and model_fields_set contains the field
        if self.last_seen is None and "last_seen" in self.model_fields_set:
            _dict['last_seen'] = None

        # set to None if mac_eth (nullable) is None
        # and model_fields_set contains the field
        if self.mac_eth is None and "mac_eth" in self.model_fields_set:
            _dict['mac_eth'] = None

        # set to None if mac_wifi (nullable) is None
        # and model_fields_set contains the field
        if self.mac_wifi is None and "mac_wifi" in self.model_fields_set:
            _dict['mac_wifi'] = None

        # set to None if memory_percent (nullable) is None
        # and model_fields_set contains the field
        if self.memory_percent is None and "memory_percent" in self.model_fields_set:
            _dict['memory_percent'] = None

        # set to None if memory_used_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.memory_used_bytes is None and "memory_used_bytes" in self.model_fields_set:
            _dict['memory_used_bytes'] = None

        # set to None if mqtt_broker_rtt_jitter_ms (nullable) is None
        # and model_fields_set contains the field
        if self.mqtt_broker_rtt_jitter_ms is None and "mqtt_broker_rtt_jitter_ms" in self.model_fields_set:
            _dict['mqtt_broker_rtt_jitter_ms'] = None

        # set to None if mqtt_broker_rtt_ms (nullable) is None
        # and model_fields_set contains the field
        if self.mqtt_broker_rtt_ms is None and "mqtt_broker_rtt_ms" in self.model_fields_set:
            _dict['mqtt_broker_rtt_ms'] = None

        # set to None if network_jitter_ms (nullable) is None
        # and model_fields_set contains the field
        if self.network_jitter_ms is None and "network_jitter_ms" in self.model_fields_set:
            _dict['network_jitter_ms'] = None

        # set to None if network_latency_ms (nullable) is None
        # and model_fields_set contains the field
        if self.network_latency_ms is None and "network_latency_ms" in self.model_fields_set:
            _dict['network_latency_ms'] = None

        # set to None if ping_jitter_ms (nullable) is None
        # and model_fields_set contains the field
        if self.ping_jitter_ms is None and "ping_jitter_ms" in self.model_fields_set:
            _dict['ping_jitter_ms'] = None

        # set to None if ping_ms (nullable) is None
        # and model_fields_set contains the field
        if self.ping_ms is None and "ping_ms" in self.model_fields_set:
            _dict['ping_ms'] = None

        # set to None if ping_p50_30m_ms (nullable) is None
        # and model_fields_set contains the field
        if self.ping_p50_30m_ms is None and "ping_p50_30m_ms" in self.model_fields_set:
            _dict['ping_p50_30m_ms'] = None

        # set to None if uptime_percent_24h (nullable) is None
        # and model_fields_set contains the field
        if self.uptime_percent_24h is None and "uptime_percent_24h" in self.model_fields_set:
            _dict['uptime_percent_24h'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config": obj.get("config"),
            "cpu_percent": obj.get("cpu_percent"),
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "ip_last": obj.get("ip_last"),
            "last_seen": obj.get("last_seen"),
            "mac_eth": obj.get("mac_eth"),
            "mac_wifi": obj.get("mac_wifi"),
            "memory_percent": obj.get("memory_percent"),
            "memory_used_bytes": obj.get("memory_used_bytes"),
            "mqtt_broker_rtt_jitter_ms": obj.get("mqtt_broker_rtt_jitter_ms"),
            "mqtt_broker_rtt_ms": obj.get("mqtt_broker_rtt_ms"),
            "name": obj.get("name"),
            "network_jitter_ms": obj.get("network_jitter_ms"),
            "network_latency_ms": obj.get("network_latency_ms"),
            "ping_jitter_ms": obj.get("ping_jitter_ms"),
            "ping_ms": obj.get("ping_ms"),
            "ping_p50_30m_ms": obj.get("ping_p50_30m_ms"),
            "status": obj.get("status"),
            "storage_used_bytes": obj.get("storage_used_bytes"),
            "uptime_percent_24h": obj.get("uptime_percent_24h"),
            "uptime_seconds": obj.get("uptime_seconds")
        })
        return _obj


