# coding: utf-8

"""
    Farm Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class NodeAds1263SettingsDraft(BaseModel):
    """
    NodeAds1263SettingsDraft
    """ # noqa: E501
    cs_bcm: Optional[StrictInt] = None
    data_rate: Optional[StrictStr] = None
    drdy_bcm: Optional[StrictInt] = None
    enabled: Optional[StrictBool] = None
    gain: Optional[StrictInt] = None
    rst_bcm: Optional[StrictInt] = None
    scan_interval_seconds: Optional[Union[StrictFloat, StrictInt]] = None
    spi_bus: Optional[StrictInt] = None
    spi_device: Optional[StrictInt] = None
    spi_mode: Optional[StrictInt] = None
    spi_speed_hz: Optional[StrictInt] = None
    vref_volts: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["cs_bcm", "data_rate", "drdy_bcm", "enabled", "gain", "rst_bcm", "scan_interval_seconds", "spi_bus", "spi_device", "spi_mode", "spi_speed_hz", "vref_volts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodeAds1263SettingsDraft from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cs_bcm (nullable) is None
        # and model_fields_set contains the field
        if self.cs_bcm is None and "cs_bcm" in self.model_fields_set:
            _dict['cs_bcm'] = None

        # set to None if data_rate (nullable) is None
        # and model_fields_set contains the field
        if self.data_rate is None and "data_rate" in self.model_fields_set:
            _dict['data_rate'] = None

        # set to None if drdy_bcm (nullable) is None
        # and model_fields_set contains the field
        if self.drdy_bcm is None and "drdy_bcm" in self.model_fields_set:
            _dict['drdy_bcm'] = None

        # set to None if gain (nullable) is None
        # and model_fields_set contains the field
        if self.gain is None and "gain" in self.model_fields_set:
            _dict['gain'] = None

        # set to None if rst_bcm (nullable) is None
        # and model_fields_set contains the field
        if self.rst_bcm is None and "rst_bcm" in self.model_fields_set:
            _dict['rst_bcm'] = None

        # set to None if scan_interval_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.scan_interval_seconds is None and "scan_interval_seconds" in self.model_fields_set:
            _dict['scan_interval_seconds'] = None

        # set to None if spi_bus (nullable) is None
        # and model_fields_set contains the field
        if self.spi_bus is None and "spi_bus" in self.model_fields_set:
            _dict['spi_bus'] = None

        # set to None if spi_device (nullable) is None
        # and model_fields_set contains the field
        if self.spi_device is None and "spi_device" in self.model_fields_set:
            _dict['spi_device'] = None

        # set to None if spi_mode (nullable) is None
        # and model_fields_set contains the field
        if self.spi_mode is None and "spi_mode" in self.model_fields_set:
            _dict['spi_mode'] = None

        # set to None if spi_speed_hz (nullable) is None
        # and model_fields_set contains the field
        if self.spi_speed_hz is None and "spi_speed_hz" in self.model_fields_set:
            _dict['spi_speed_hz'] = None

        # set to None if vref_volts (nullable) is None
        # and model_fields_set contains the field
        if self.vref_volts is None and "vref_volts" in self.model_fields_set:
            _dict['vref_volts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodeAds1263SettingsDraft from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cs_bcm": obj.get("cs_bcm"),
            "data_rate": obj.get("data_rate"),
            "drdy_bcm": obj.get("drdy_bcm"),
            "enabled": obj.get("enabled"),
            "gain": obj.get("gain"),
            "rst_bcm": obj.get("rst_bcm"),
            "scan_interval_seconds": obj.get("scan_interval_seconds"),
            "spi_bus": obj.get("spi_bus"),
            "spi_device": obj.get("spi_device"),
            "spi_mode": obj.get("spi_mode"),
            "spi_speed_hz": obj.get("spi_speed_hz"),
            "vref_volts": obj.get("vref_volts")
        })
        return _obj


