# coding: utf-8

"""
    Farm Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class OfflineMapPackResponse(BaseModel):
    """
    OfflineMapPackResponse
    """ # noqa: E501
    bounds: Optional[Any]
    error: Optional[StrictStr] = None
    id: StrictStr
    max_zoom: StrictInt
    min_zoom: StrictInt
    name: StrictStr
    progress: Optional[Any]
    status: StrictStr
    updated_at: StrictStr
    __properties: ClassVar[List[str]] = ["bounds", "error", "id", "max_zoom", "min_zoom", "name", "progress", "status", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OfflineMapPackResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if bounds (nullable) is None
        # and model_fields_set contains the field
        if self.bounds is None and "bounds" in self.model_fields_set:
            _dict['bounds'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if progress (nullable) is None
        # and model_fields_set contains the field
        if self.progress is None and "progress" in self.model_fields_set:
            _dict['progress'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OfflineMapPackResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bounds": obj.get("bounds"),
            "error": obj.get("error"),
            "id": obj.get("id"),
            "max_zoom": obj.get("max_zoom"),
            "min_zoom": obj.get("min_zoom"),
            "name": obj.get("name"),
            "progress": obj.get("progress"),
            "status": obj.get("status"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


