# coding: utf-8

"""
    Infrastructure Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class OutputCreateRequest(BaseModel):
    """
    OutputCreateRequest
    """ # noqa: E501
    command_topic: Optional[StrictStr] = None
    config: Optional[Any] = None
    history: Optional[List[Any]] = None
    id: Optional[StrictStr] = None
    last_command: Optional[StrictStr] = None
    name: StrictStr
    node_id: UUID
    schedule_ids: Optional[List[StrictStr]] = None
    state: Optional[StrictStr] = None
    supported_states: Optional[List[StrictStr]] = None
    type: StrictStr
    __properties: ClassVar[List[str]] = ["command_topic", "config", "history", "id", "last_command", "name", "node_id", "schedule_ids", "state", "supported_states", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OutputCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if command_topic (nullable) is None
        # and model_fields_set contains the field
        if self.command_topic is None and "command_topic" in self.model_fields_set:
            _dict['command_topic'] = None

        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if last_command (nullable) is None
        # and model_fields_set contains the field
        if self.last_command is None and "last_command" in self.model_fields_set:
            _dict['last_command'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OutputCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "command_topic": obj.get("command_topic"),
            "config": obj.get("config"),
            "history": obj.get("history"),
            "id": obj.get("id"),
            "last_command": obj.get("last_command"),
            "name": obj.get("name"),
            "node_id": obj.get("node_id"),
            "schedule_ids": obj.get("schedule_ids"),
            "state": obj.get("state"),
            "supported_states": obj.get("supported_states"),
            "type": obj.get("type")
        })
        return _obj


