# coding: utf-8

"""
    Farm Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from generated_api.models.event_polarity_v1 import EventPolarityV1
from typing import Optional, Set
from typing_extensions import Self

class PreviewEventOverlayParamsV1(BaseModel):
    """
    PreviewEventOverlayParamsV1
    """ # noqa: E501
    gap_max_buckets: Optional[StrictInt] = None
    max_events: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    min_separation_buckets: Optional[StrictInt] = None
    polarity: Optional[EventPolarityV1] = None
    tolerance_seconds: Optional[StrictInt] = None
    z_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["gap_max_buckets", "max_events", "min_separation_buckets", "polarity", "tolerance_seconds", "z_threshold"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PreviewEventOverlayParamsV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if gap_max_buckets (nullable) is None
        # and model_fields_set contains the field
        if self.gap_max_buckets is None and "gap_max_buckets" in self.model_fields_set:
            _dict['gap_max_buckets'] = None

        # set to None if max_events (nullable) is None
        # and model_fields_set contains the field
        if self.max_events is None and "max_events" in self.model_fields_set:
            _dict['max_events'] = None

        # set to None if min_separation_buckets (nullable) is None
        # and model_fields_set contains the field
        if self.min_separation_buckets is None and "min_separation_buckets" in self.model_fields_set:
            _dict['min_separation_buckets'] = None

        # set to None if polarity (nullable) is None
        # and model_fields_set contains the field
        if self.polarity is None and "polarity" in self.model_fields_set:
            _dict['polarity'] = None

        # set to None if tolerance_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.tolerance_seconds is None and "tolerance_seconds" in self.model_fields_set:
            _dict['tolerance_seconds'] = None

        # set to None if z_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.z_threshold is None and "z_threshold" in self.model_fields_set:
            _dict['z_threshold'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PreviewEventOverlayParamsV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gap_max_buckets": obj.get("gap_max_buckets"),
            "max_events": obj.get("max_events"),
            "min_separation_buckets": obj.get("min_separation_buckets"),
            "polarity": obj.get("polarity"),
            "tolerance_seconds": obj.get("tolerance_seconds"),
            "z_threshold": obj.get("z_threshold")
        })
        return _obj


