# coding: utf-8

"""
    Infrastructure Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SensorUpdateRequest(BaseModel):
    """
    SensorUpdateRequest
    """ # noqa: E501
    config: Optional[Any] = None
    deleted_at: Optional[StrictStr] = None
    interval_seconds: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    rolling_avg_seconds: Optional[StrictInt] = None
    type: Optional[StrictStr] = None
    unit: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["config", "deleted_at", "interval_seconds", "name", "rolling_avg_seconds", "type", "unit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SensorUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        # set to None if interval_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.interval_seconds is None and "interval_seconds" in self.model_fields_set:
            _dict['interval_seconds'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if rolling_avg_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.rolling_avg_seconds is None and "rolling_avg_seconds" in self.model_fields_set:
            _dict['rolling_avg_seconds'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if unit (nullable) is None
        # and model_fields_set contains the field
        if self.unit is None and "unit" in self.model_fields_set:
            _dict['unit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SensorUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config": obj.get("config"),
            "deleted_at": obj.get("deleted_at"),
            "interval_seconds": obj.get("interval_seconds"),
            "name": obj.get("name"),
            "rolling_avg_seconds": obj.get("rolling_avg_seconds"),
            "type": obj.get("type"),
            "unit": obj.get("unit")
        })
        return _obj


