# coding: utf-8

"""
    Farm Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from generated_api.models.preview_event_overlays_v1 import PreviewEventOverlaysV1
from generated_api.models.tsse_episode_v1 import TsseEpisodeV1
from generated_api.models.tsse_preview_series_v1 import TssePreviewSeriesV1
from typing import Optional, Set
from typing_extensions import Self

class TssePreviewResponseV1(BaseModel):
    """
    TssePreviewResponseV1
    """ # noqa: E501
    bucket_seconds: StrictInt
    candidate: TssePreviewSeriesV1
    candidate_aligned: Optional[TssePreviewSeriesV1] = None
    event_overlays: Optional[PreviewEventOverlaysV1] = None
    focus: TssePreviewSeriesV1
    selected_episode: Optional[TsseEpisodeV1] = None
    __properties: ClassVar[List[str]] = ["bucket_seconds", "candidate", "candidate_aligned", "event_overlays", "focus", "selected_episode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TssePreviewResponseV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of candidate
        if self.candidate:
            _dict['candidate'] = self.candidate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of candidate_aligned
        if self.candidate_aligned:
            _dict['candidate_aligned'] = self.candidate_aligned.to_dict()
        # override the default output from pydantic by calling `to_dict()` of event_overlays
        if self.event_overlays:
            _dict['event_overlays'] = self.event_overlays.to_dict()
        # override the default output from pydantic by calling `to_dict()` of focus
        if self.focus:
            _dict['focus'] = self.focus.to_dict()
        # override the default output from pydantic by calling `to_dict()` of selected_episode
        if self.selected_episode:
            _dict['selected_episode'] = self.selected_episode.to_dict()
        # set to None if candidate_aligned (nullable) is None
        # and model_fields_set contains the field
        if self.candidate_aligned is None and "candidate_aligned" in self.model_fields_set:
            _dict['candidate_aligned'] = None

        # set to None if event_overlays (nullable) is None
        # and model_fields_set contains the field
        if self.event_overlays is None and "event_overlays" in self.model_fields_set:
            _dict['event_overlays'] = None

        # set to None if selected_episode (nullable) is None
        # and model_fields_set contains the field
        if self.selected_episode is None and "selected_episode" in self.model_fields_set:
            _dict['selected_episode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TssePreviewResponseV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bucket_seconds": obj.get("bucket_seconds"),
            "candidate": TssePreviewSeriesV1.from_dict(obj["candidate"]) if obj.get("candidate") is not None else None,
            "candidate_aligned": TssePreviewSeriesV1.from_dict(obj["candidate_aligned"]) if obj.get("candidate_aligned") is not None else None,
            "event_overlays": PreviewEventOverlaysV1.from_dict(obj["event_overlays"]) if obj.get("event_overlays") is not None else None,
            "focus": TssePreviewSeriesV1.from_dict(obj["focus"]) if obj.get("focus") is not None else None,
            "selected_episode": TsseEpisodeV1.from_dict(obj["selected_episode"]) if obj.get("selected_episode") is not None else None
        })
        return _obj


