# coding: utf-8

"""
    Infrastructure Dashboard Core Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from generated_api.models.ws2902_protocol import Ws2902Protocol
from typing import Optional, Set
from typing_extensions import Self

class Ws2902StatusResponse(BaseModel):
    """
    Ws2902StatusResponse
    """ # noqa: E501
    created_at: StrictStr
    enabled: StrictBool
    id: StrictStr
    ingest_path_template: StrictStr
    last_missing_fields: List[StrictStr]
    last_payload: Optional[Any] = None
    last_seen: Optional[StrictStr] = None
    nickname: StrictStr
    node_id: StrictStr
    protocol: Ws2902Protocol
    rotated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_at", "enabled", "id", "ingest_path_template", "last_missing_fields", "last_payload", "last_seen", "nickname", "node_id", "protocol", "rotated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Ws2902StatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_payload (nullable) is None
        # and model_fields_set contains the field
        if self.last_payload is None and "last_payload" in self.model_fields_set:
            _dict['last_payload'] = None

        # set to None if last_seen (nullable) is None
        # and model_fields_set contains the field
        if self.last_seen is None and "last_seen" in self.model_fields_set:
            _dict['last_seen'] = None

        # set to None if rotated_at (nullable) is None
        # and model_fields_set contains the field
        if self.rotated_at is None and "rotated_at" in self.model_fields_set:
            _dict['rotated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Ws2902StatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "enabled": obj.get("enabled"),
            "id": obj.get("id"),
            "ingest_path_template": obj.get("ingest_path_template"),
            "last_missing_fields": obj.get("last_missing_fields"),
            "last_payload": obj.get("last_payload"),
            "last_seen": obj.get("last_seen"),
            "nickname": obj.get("nickname"),
            "node_id": obj.get("node_id"),
            "protocol": obj.get("protocol"),
            "rotated_at": obj.get("rotated_at")
        })
        return _obj


